### ISSUE TITLE
Cannot initialize effect engine, Error: -3

### ISSUE THREAD

**Issue by hakendog** [google/oboe#1000]
Android version(s):pie (API 28)
Android device(s): pixel 2
Oboe version:1.4.3
App name used for testing: OboeTester

I'm trying to add effects to Oboe.
Specifically, uncomment line 87 of TestOutputActivityBase.java.

https://github.com/google/oboe/blob/d008ab660a9059a1b69ae870f853afd2d8e0cd0e/apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestOutputActivityBase.java#L87

But when I check the Effect and start the stream it will prompt for
Cannot initialize effect engine for type: 7261676f-6d75-7369-6364-28e2fd3ac39e Error: -3

Is there a step I'm doing wrong?
I need your help. Thank you.

**Comment by philburk** [comment]
Did you check the Effects[] checkbox on the TEST OUTPUT screen?
That will tell AAudio to allocate a SessionID,
which will result in using a Legacy stream.

**Comment by hakendog** [comment]
> Did you check the Effects[] checkbox on the TEST OUTPUT screen?
> That will tell AAudio to allocate a SessionID,
> which will result in using a Legacy stream.

Yes, I have checked the "Effects" checkbox.

But it still shows the toast message "Cannot initialize effect engine, Error: -3".

**Comment by mortalis13** [comment]
The same error in the latest **OboeTester** app.
The `setupEffects()` method moved here:
https://github.com/google/oboe/blob/3712ef65aec552d766271cdf4f5e3a0660295737/apps/OboeTester/app/src/main/java/com/mobileer/oboetester/StreamConfigurationView.java#L536

Steps to reproduce:
- open app
- press **Test Output**
- check **Effect**
- press **Open**
- toast is shown **"Cannot initialize effect engine..."**
- the logcat shows this block:
```
E AudioEffect: set(): AudioFlinger could not create effect 0634f220-ddd4-11db-a0fc-0002a5d5c51b / ec7178ec-e5e1-4432-a3f4-4657e6795210, status: -22
E AudioEffects-JNI: AudioEffect initCheck failed -3
E AudioEffect-JAVA: Error code -3 when initializing AudioEffect.
E OboeTester: Error: Cannot initialize effect engine for type: 0634f220-ddd4-11db-a0fc-0002a5d5c51b Error: -3
```

Trying to simplify the method, I first removed all the code from it adding only one line for debugging `Log.i(TAG, "--setupEffects(), sessionId: " + sessionId);`.
After repeating the mentioned steps, the error is not shown, the logcat has this line:
```
--setupEffects(), sessionId: 55257
```

Next, added a simple `Equalizer` init, like this:
```
public void setupEffects(int sessionId) {
    Log.i(TAG, "--setupEffects()");
    Equalizer eq = new Equalizer(0, sessionId);
}
```

The same error repeats, with a different effect ID of course:
```
I StreamConfigurationView: --setupEffects(), sessionId: 55265
E AudioEffect: set(): AudioFlinger could not create effect 0bed4300-ddd6-11db-8f34-0002a5d5c51b / ec7178ec-e5e1-4432-a3f4-4657e6795210, status: -22
E AudioEffects-JNI: AudioEffect initCheck failed -3
E AudioEffect-JAVA: Error code -3 when initializing AudioEffect.
E OboeTester: Error: Cannot initialize effect engine for type: 0bed4300-ddd6-11db-8f34-0002a5d5c51b Error: -3
```

Checking the internet for the error description, the first thing I found was this: https://stackoverflow.com/questions/39821027
where an incorrect session ID is passed to the effect constructor.

Maybe it has something to do with the session ID, although the IDs generated during this test were not 0.

So can this thing be fixed please? So that we have a working example of basic effects.
Thanks.

**Comment by mortalis13** [comment]
Found another related issue here
https://github.com/jrfeng/snow/issues/17#issuecomment-748112336
which apparently was fixed, but it's unknown how...

**Comment by robertwu1** [comment]
@mortalis13 try setting PerformanceMode to None instead of LowLatency. Effects are not supported for LowLatency.

**Comment by philburk** [comment]
This is a suitable workaround for old Android versions.
If AAudio cannot use the sessionID in LowLatency mode then it should downgrade automatically to None.
Please file a bug internally for AAudio.

**Comment by philburk** [comment]
> Please file a bug internally for AAudio.

We decided not to do this because AAudio will create a working stream in LowLatency mode.
The app just can't attach an effect to that StreamId.
