### ISSUE TITLE
sample accurate metronome

### ISSUE THREAD

**Issue by mgood7123** [google/oboe#1099]
is it possible to make a sample-accurate metronome using the oboe?

for purposes such as `DAW` use and `step sequencer/piano roll` use

if so, how might this be set up and what might it look like?

**Comment by philburk** [comment]
> is it possible to make a sample-accurate metronome using the oboe?

Yes. You just have to render your metronome ticks at the right place in the audio stream. As long as the stream plays without glitches then your metronome will be stable. You do not need a low latency stream for this because the user is not interacting closely with the metronome.

For example, here is some very simplified code to render a metronome tick every half second:

    const int32_t period = sampleRate / 2;

    phase++;
    if (phase >= period) {
        phase = 0;
        output = 1.0;
    } else {
        output = 0.0;
    }

**Comment by dturner** [comment]
RhythmGame plays a "clap" sound with frame accuracy. It does this inside the data callback by creating a loop from 0 to `numFrames` and checking on each iteration whether a clap sound should be played: https://github.com/google/oboe/blob/master/samples/RhythmGame/src/main/cpp/Game.cpp#L131
