### ISSUE TITLE
How to gauge audio latency accurately enough for vocals

### ISSUE THREAD

**Issue by appinica** [google/oboe#1129]
This is more of a feasibility question as opposed to an actual issue.

My app is designed to enable collaborative singing, so you start by recording yourself (video from front facing and audio too of course). Once finished your friend on their phone can then play back the first recording and sing along to it (earphones plugged in for mic and listening with one earbud). Then I stack the videos together and mix the audio streams. The problem is when you play back the resulting video the audio streams are not in sync with each other. There's a 44ms (seems to be the average from testing) offset.

So I'm putting this down to the latency from the input from the mic and then processing on the audio (there must be a small gap too stemming from not being able to play the video and record at precisely the same time).

If I knew what the input/processing latency is then it's easy to programmatically shift the tracks so they line up... But that's where I'm stuck as I don't know if it's possible to actually get a concrete figure for the latency as presumably it will vary during the audio recording. Can I use Oboe to get some gauge of the latency? Or maybe what I'm trying is simply not possible with Android at this current time.

To be clear my app isn't even using Oboe yet, but when researching the area of audio latency on Android Oboe is the first thing that jumped out to me, so figured here was a good place to start.

Thanks for any and all feedback.

**Comment by dturner** [comment]
Let me make sure I have this clear:

* User A records a video of themself singing. The audio and video are perfectly in sync. 
* They share the video via the app to user B
* User B plays user A's video, listening to the audio through headphones
* At the same time they record a video of them singing into the built-in microphone
* Once finished the app stitches the audio from the 2 videos together, however, the audio is out of sync by around 44ms. 

Is that correct? 

If so, the biggest source of latency is going to be the _output_ latency, the time it takes the audio from user A's video to reach user B's headphones. 

Is there a way of calculating the output latency? Yes :) And here's a code sample: https://github.com/google/oboe/blob/master/samples/hello-oboe/src/main/cpp/HelloOboeEngine.cpp#L42. I also went into more detail about the technique in [this SO answer](https://stackoverflow.com/questions/48687470/audio-latency-issues/48773125#48773125).

You should be able to use the same technique to obtain the input latency, although input latency is typically much smaller (3-5ms in my experience) so might not be enough of an issue to be concerned about. 

Once you have the latency you can offset user B's audio by that amount in order to get perfect synchronisation.

**Comment by appinica** [comment]
Hi Don,

Thanks for your comment and help, and the SO link. Both of which look like they will help me tune the synchronisation of the audio tracks. I definitely was thinking about the latency round the wrong way.

Cheers!
