### ISSUE TITLE
samples/LiveEffect crashes on exit

### ISSUE THREAD

**Issue by zhenyuni** [google/oboe#1143]
Android version(s): All
Android device(s): All
Oboe version: 1.5
App name used for testing: samples/LiveEffect
 
**Short description**
The sample crashes on exit.

**Steps to reproduce**
 - Run the `LiveEffect` sample
 - Click `Start` and then `Stop`
 - Press the phone back button
 - Read the logcat

**Expected behavior**
No crash

**Actual behavior**
It crashed

**Device**
Pixel 2 XL, vivo Nex A, etc

**Comment by philburk** [comment]
Thanks for the report.  

I tried to reproduce this on a Pixel 4a 5G on S.
It did not crash on exit. Perhaps because it was using MMAP.
I disabled MMAP using:

    adb shell setprop aaudio.mmap_policy 1

and it still did not crash.

I then tried on a Pixel 2 XL running 9.0, Pie. No crash.

@zhenyuni - Can you please include an error message and stack dump from the crash?
Also please provide a specific device and Android version.

**Comment by zhenyuni** [comment]
I am sorry I wasn't running the latest code. This problem has been fixed in 00039f7 by removing destructor of LiveEffectEngine. It works fine now. 
Please close this issue. Sorry again.
