### ISSUE TITLE
AAudio shared MMAP streams do not disconnect properly on RQ1A when headset plugged in

### ISSUE THREAD

**Issue by philburk** [google/oboe#1145]
See public Android bug for more details.

https://issuetracker.google.com/issues/173928197

**Comment by peterdk** [comment]
I am a bit confused about if I am experiencing this issue.
I am testing Oboe on a Pixel 3a, with Android 11, and Oboe does get a TIMEOUT when I connect a headphone while running my app.
```
W/AudioStreamInternal_Client: processData(): entered at 1065621368028 nanos, currently 1066621176044
2021-01-31 17:03:03.074 11725-11834/umito.android.minipiano W/AudioStreamInternal_Client: processData(): TIMEOUT after 1000000000 nanos
2021-01-31 17:03:03.074 11725-11834/umito.android.minipiano W/AudioStreamInternal_Client: processData(): wakeTime = 1066621376044, deadline = 1066621368028 nanos
2021-01-31 17:03:03.074 11725-11834/umito.android.minipiano W/AudioStreamInternal_Client: processData(): past deadline by 8 micros
```
My error callback returns 'false' so I expect Oboe to restart itself. However, it only shuts down and so no sound is heard anymore.

Am I right that I should expect Oboe to restart itself? 

I tried the OboeTester app and there the disconnects are detected properly. I used git master of Oboe for that tester, and also used master for integrating Oboe instead of 1.5.0 to see if it was fixed already. Unfortunately in my own app, it just shuts down.

**Comment by peterdk** [comment]
Never mind, I seem to need to call my start() logic in onErrorAfterClose. Oboe doesn't auto restart apparently.

**Comment by philburk** [comment]
Right. Oboe does not automatically restart the stream when it is disconnected.
You can do that yourself from onErrorAfterClose().

If you need to control the locking more carefully then consider using the new callback classes in Oboe 1.5.0.
You can override the [onError()](https://google.github.io/oboe/reference/classoboe_1_1_audio_stream_error_callback.html) method to stop, close, reopen and restart all under one lock.

**Comment by philburk** [comment]
This was fixed in RQ2A.
