### ISSUE TITLE
C compatible API header for liboboe

### ISSUE THREAD

**Issue by gkongd** [google/oboe#1248]
Greetings,

I'm currently working on an AAudio Delphi Object Pascal wrapper, however according to the NDK documentation, developers are encouraged to use liboboe instead.
Since some C++ language specific constructs can be difficult to translate when wrapping the calls, a plain C API header is easier to use as a foundation for translations.
It seems one point in time, liboboe was renamed to libaaudio?

The question though, is it possible to offer a C API header file together with the releases, or is the existing aaudio.h close enough that it can be used as a basis for interacting with liboboe exported functions?

This is my first interactions with this library, so please forgive my ignorance.

**Comment by philburk** [comment]
We do encourage developers to use Oboe instead of AAudio directly because Oboe works with OpenSL ES on old devices. Also Oboe has workaround for bugs on various devices.

Oboe is a thin wrapper over the AAudio API.  So a C API similar to AAudio that called Oboe would work well and be easy to implement. You could pass the object pointers back to Pascal as 64-bit integers or create integer handles.

> It seems one point in time, liboboe was renamed to libaaudio?

The prototype was an external library called Oboe. It then split into the AAudio NDK library and the Oboe support library.
