### ISSUE TITLE
getSampleRate disagrees with getFramesRead for input streams when sample rate conversion is enabled

### ISSUE THREAD

**Issue by chrismanchester** [google/oboe#1256]
The calculation here: https://github.com/google/oboe/blob/8041b3891ade1a39dc575fb4e740b6d6f7087d0d/src/common/FilterAudioStream.cpp#L51 makes a ratio that will convert from output to input sample rate. However, `getSampleRate` will always report the requested (converted) sample rate, which is the input sample rate for an output stream, but the output sample rate for an input stream. This means calculations working with `getSampleRate` along with `getFramesRead` on input streams will yield incorrect values. Changing the value of `mRateScaler` to `((double) getSampleRate()) / mChildStream->getSampleRate();` appears to resolve this issue, by setting up a ratio that will consistently convert from the child (native) sample rate to the software (converted) sample rate.

To demonstrate the problem, if we make a function that calculates latency for a stream based on AudioStreamAAudio's calculateLatencyMillis, it will produce implausibly small or negative values for latency when calculating for an input stream that's converting from 48k to 44.1k.

**Comment by philburk** [comment]
Thank you for reporting this problem with mRateScaler. You are correct. We will fix that.

The best way to REPRODUCE the problem is:
* Launch OboeTester
* Tap TEST INPUT
* Select SRate: 8000
* Select Convert:  SRC:  Medium
* Tap OPEN, START
* Wait 10 seconds
* Tap STOP
* Look at Frames read and frames written

EXPECT: about 10*8000 = 80,000 frames

ACTUAL:  about 3,200,000 frames

We should fix this and also add a unit test to detect it.

**Comment by philburk** [comment]
Reopening for unit tests.
