### ISSUE TITLE
Inconsistent callbacks at 10 milliseconds.  

### ISSUE THREAD

**Issue by Slahuddin-Ch** [google/oboe#1326]
Android version(s):
All versions

Android device(s):
All devices 

Oboe version:
oboe-1.5-stable
oboe-1.6-stable

**Short description**

Callbacks at 10 ms are very inconsistent. at 20ms and 40 ms callbacks shows consistent behavior. 

**Results at 10 ms** 

setSampleRate = 48000
setFramesPerDataCallback 480 (10ms)
fluctuate between (0 ms - 40ms)

**Results at 20 ms** 

setSampleRate = 48000
setFramesPerDataCallback 960 (20ms)
fluctuate between (19 ms - 21ms)

**Results at 40 ms** 

setSampleRate = 48000
setFramesPerDataCallback 1920 (10ms)
fluctuate between (39 ms - 41 ms)

**Steps to reproduce**
Set Sample rate [48000]([url](url))
Set frames per callback 480 (10ms)
print a log in onAudioReady

**Expected behavior**
callbacks at 10ms should be stable

[result 10 ms .txt](https://github.com/google/oboe/files/6757906/result.10.ms.txt)
[result 20 ms .txt](https://github.com/google/oboe/files/6757907/result.20.ms.txt)
[result 40 ms .txt](https://github.com/google/oboe/files/6757908/result.40.ms.txt)

**Comment by philburk** [comment]
This behavior is expected when using setFramesPerDataCallback().

The underlying software or hardware is still calling Oboe at an interval determined by framesPerBurst.
Imagine if the burst is 1924 frames. When Oboe is called, it will call your app callback multiple times in order to fill the burst. Then it will wait for another burst period.  So the timing between the callbacks your apps sees will vary from 0 to the burst period.

Oboe might call your app a different number of times depending on the combination of burst size and callback size.  This becomes even more complicated when sample rate conversion is involved because that adds another ratio of buffer sizes.

Calling setFramesPerDataCallback() does not guarantee anything about timing. It just collects the data into a the number of frames that you app requires.

We should document this better.

**Comment by Slahuddin-Ch** [comment]
Thanks, @philburk for the quick response. Is there a way we can guarantee anything about timing?

**Comment by philburk** [comment]
We cannot guarantee callback timing. But you can improve timing regularity by avoiding setFramesPerDataCallback(). Also avoid sample rate conversion by not specifying a sample rate and just letting Oboe chose the best native rate. (The native rate is almost always going to be 48000 Hz.)
