### ISSUE TITLE
SM-G977B fails "Test Disconnects" on Android 11

### ISSUE THREAD

**Issue by chrismanchester** [google/oboe#1350]
Android version(s): 11
Android device(s): SM-G977B
Oboe version: 1.6.0
App name used for testing: OboeTester
 
**Short description**
S10 5G device fails to receive stream disconnects consistent with this [note](https://github.com/google/oboe/blob/main/docs/notes/disconnect.md) despite using Android 11.

**Steps to reproduce**
Run "Test Disconnects" test from OboeTester and observe failures (log attached)

**Expected behavior**
onError callbacks are called consistently when input or output devices change.

**Actual behavior**
We don't receive any callbacks, consistent with test failures from OboeTester.

**Device**
SM-G977B

**Any additional context**

Log here:
[oboeTester.txt](https://github.com/google/oboe/files/6826824/oboeTester.txt)

**Comment by philburk** [comment]
Thanks for using OboeTester. It is detecting the UNplug event but not the plugIN event.
I see that the MMAP LowLatency streams are failing but the test was stopped before the Legacy streams were tested.

There is a known issue in P. I can see from the oboeTester.txt file that the device is running PPR1.180610.011.G977BXXU1ASEC

We have also seen this in some early versions of Q but it was fixed in Q. See #893

Android 11 is R. Have you also seen this on a device running R?

**Comment by chrismanchester** [comment]
Hi Phil, thanks for taking a look at this issue. I received this log and report from a colleague who reported the device was running Android 11, but they must have been mistaken. I will close this and re-open if we end up confirming this on a device running R. Thank you!
