### ISSUE TITLE
AudioStreamAAudio::getTimestamp(CLOCK_MONOTONIC) returns same value across successive onAudioReady calls

### ISSUE THREAD

**Issue by mazbox** [google/oboe#1462]
Android version(s): 11
Android device(s): Pixel 3a
Oboe version: 1.6.1

**Short description**
When calling outputStream->getTimestamp() in the onAudioReady callback, the clock is the same value for 24 or so calls before updating.
```

oboe::DataCallbackResult
    onAudioReady(oboe::AudioStream *outputStream, void *audioData, int32_t numFrames) override {
        //virtual ResultWithValue<FrameTimestamp>

        // def dunno if it's good to call this
        if(auto tsRes = outputStream->getTimestamp(CLOCK_MONOTONIC)) {
            outputTime = tsRes.value().timestamp;
            Log::d() << tsRes.value().timestamp << tsRes.value().position;
        }
     ...
}
```

Shouldn't the clock update between callbacks?

**Comment by philburk** [comment]
This is expected behavior. The time stamps are generated by low level code
and they're only updated periodically. Because the audio is isochronous you
can extrapolate from the last timestamp to estimate when a particular frame
will be played.

We should update the documentation to explain this better.

**Comment by mazbox** [comment]
Ah ok, already tried that and it seems to work nicely. Another small point on the docs - It took me a while to figure out that the clock is only available in AAudio, but I think that’s a separate ticket here
