### ISSUE TITLE
The best latency to achieve when try to record audio stream and video stream synchronously

### ISSUE THREAD

**Issue by sunwell1994** [google/oboe#1463]
Hi, I have tried the great Oboe tester and the latency is about **4~8 milliseconds.** 
I am curious about whether we can achieve **a delay of microseconds** level with the best practice to sync the video and audio stream when recording both streams? If so, how can we take advantage of current APIs? Thanks!

**Comment by robertwu1** [comment]
We are not able to reach microseconds. A 4ms buffer is required as we double buffer audio.

Audio-video sync is done on multiple levels throughout Android. One thing you can notice is that audio can be slightly behind video and the results are not noticeable. It's because audio moves at a slow rate in a room, at ~343m/s
