### ISSUE TITLE
portaudio or RtAudio-style API

### ISSUE THREAD

**Issue by mazbox** [google/oboe#1479]
Hi oboe team!

I was wondering why the oboe API needs to be so complicated? Having used RtAudio and portaudio in the past, their API's seem sensible and are remarkably stable across the platforms they support. I've also written my own API for iOS, which was relatively easy and very robust.

Oboe seems to require a very delicate choreography of classes to get it working, where a single class with a handful of methods would suffice - I've even tried to wrap oboe into such a class but for some reason, there's always some edge case that causes a problem, and I take a few days (on day 3 right now) trying to work out why something that was working has stopped working.

Even the sample code in the repo seems a lot more complicated than they could be - e.g. LiveEffect is full of boilerplate code - I concede that having oboe the way it is leads to it being more flexible, but surely a better API design would be to allow users to opt-in to more flexibility if they needed it?

all the best

Marek

**Comment by philburk** [comment]
> Having used RtAudio and portaudio in the past, their API's seem sensible and
> are remarkably stable across the platforms they support.

Thank you. I co-founded the PortAudio project with Ross Bencina. AAudio is based on the PortAudio API model. Oboe is a C++ version of that.

Oboe and AAudio are based on the builder design pattern. You create a stream using the builder and then operate on the stream. So that requires two classes. We also added a callback class.

There are some other classes that can be used with Oboe but they are mostly optional.

Are there any particular classes that you think are unnecessary that we could remove?

>  (on day 3 right now) trying to work out why something that was working has stopped working.

Feel free to file an Issue or start a discussion for the specific problem.

**Comment by mazbox** [comment]
Hey @philburk, thanks for the response! I know about your involvement with portaudio, and must say a massive thank you because I've been using it for nigh on 20 years for countless projects, including koala's Mac, windows and linux's versions, and even some projects for Google and Apple - it was my gateway into making computers make noises all those years ago.

The builder pattern is great, it makes a lot of sense. The extra classes thing I was referring to was more about the LiveEffect example - not only is there a callback object, FullDuplexPass, but it also inherits from FullDuplexStream. If you wanted to do the same with portaudio, you'd be looking at very few lines of code, like 20-30? One thing that is left on the user side is to collect enough input samples to cushion for underruns, which could somehow be on the library side maybe? Or maybe the idea is to encourage use of the reference implementation in FullDuplexStream? 

I appreciate that on Android you're going to want a lot of error checking because there's so many things that can go wrong, and there is some extra stuff that the user may want to control, but my oboe glue code is about 400 lines, compared to my portaudio code which is ~100.

The problem with trying to get help with what I'm stuck with at the moment is that its a bit of a tangle, so I'm trying to make the simplest case into a project in part to check I'm doing all the right things - if I still can't crack it then this simplified test case could be a starting point to get some help.

**Comment by philburk** [comment]
PortAudio does provide full duplex streams. But it is very hard to do and sometimes it does not work very well.
My current philosophy is that if a feature does not have to be implemented at a certain level then push it up to a higher level. For example, an OS is required to do heap allocation, device access, resource sharing, IPC, etc.
But you don't need an OS to do reverb. So that is best done at a higher level.

The full duplex stream is so tricky, and app specific, then I think it is better to give the app developer full control.
It may be more work but the app developer will have the ability to tune it properly.

If we ever nail this problem and have a foolproof full-duplex implementation that always works then we may move it down into Oboe as an optional convenience.

> not only is there a callback object, FullDuplexPass, but it also inherits from FullDuplexStream.

Yes. The Callback class and the FullDuplexStream are generic classes that can be used in many apps. FullDuplexPass is a LiveEffect specific class that just passes input to output. That class is only useful in the example code.
