### ISSUE TITLE
Can't add audio effects in live stream

### ISSUE THREAD

**Issue by YogarajRamesh** [google/oboe#1510]
Android version(s): 11
Android device(s): Realme 3 pro
Oboe version: 1.6.1

Short description
Is it possible to add audio effect in oboe:audioStream
(already i did live feedback and record voice. now i need to add echo effects to the stream )

Is it possible to add fxlab effects to LiveEffectEngine?

Device

Realme 3 pro

**Comment by robertwu1** [comment]
Take a look at the [source code](https://github.com/google/oboe/tree/main/apps/fxlab) for fxlab. Fxlab was written based on the LiveEffect sample. Try playing around with the source code of the fxlab app to see if it gives you what you need. I know its based on Kotlin instead of Java for LiveEffect, but the ideas are quite similar. Also, the native c++ code is quite similar.

LiveEffect was written as a sample so we are intentionally trying to keep it small. Feel free to add similar code to fxlab in your app.

**Comment by YogarajRamesh** [comment]
Thanks for your response

 I had recorded(using callback) with echo effects using fxlab in my app but the output recording doesn't have any echo effect. It has only default stream. Is there  anyway to add effects to the output audio.

**Comment by philburk** [comment]
See duplicate question at #1508
Please only ask a question in one place.
