### ISSUE TITLE
oboe 1.6.1 next version request with fixes

### ISSUE THREAD

**Issue by Diljeet** [google/oboe#1576]
Hello Sir @philburk & other devs
It's been while since oboe 1.6.1 got updated
There have been many fixes since then
-
Are you planning to rollout the current fixes to new oboe version, if yes when will it come out
-
I have 1 more question sir - will it be better to copy the main branch of oboe and put it in the app? or should i be using the old 1.6.1 version of oboe. Please guide me on this one
I want to copy the latest code from github main branch, is it ok or should i use the last release version 1.6.1
-
Waiting for your response
Thanks again for this wonderful work
-
@danryu Sir i deleted my comment from the other issue thread

**Comment by philburk** [comment]
@Diljeet - I agree, we need to release a new version ASAP. We are wrapping up some changes and hope to do this soon. 
We are tracking the changes here:
https://github.com/google/oboe/milestone/9

Releasing Oboe is a complicated process. I would like to release Oboe much more often. So we need to streamline that process.

> I want to copy the latest code from github main branch, is it ok or should i use the last release version 1.6.1

That is totally fine. We try to keep the main branch stable. And there are many improvements since 1.6.1.

I would check out the current copy and then test it for a while before releasing.
Keep an eye on the changes in case we fix a bug.

I am closing this as answered because we already have a milestone for tracking the release.

**Comment by Diljeet** [comment]
@philburk Thank you sir for the very clear answer
Sorry for disturbing you
Thanks for the work
----
I want to give one suggestion
You are not releasing major stable version of app, because you have incomplete work or because some issues are still pending to be fixed.
BUT you can release, not minor build like oboe 1.6.1.1 to 1.6.1.2  ...... to 1.6.1.99 till the version 1.6.2 is ready, you can call them beta or pre-release or snapshots.
Similar to FFmpeg - they release weekly or monthly snapshots and when they have a ready stable version they release it under stable version, i.e. when the stable version is not ready, they release snapshots with small changes.
-
I hope you and the team can do the same and release snapshot versions, which may have few bug fixes and improvement, so users can stay updated.
