### ISSUE TITLE
Noise in OpenSL playing when app run in background

### ISSUE THREAD

**Issue by AlphaHans** [google/oboe#1642]
Android version(s): 11 
Android device(s): OnePlus 8 (OnePlus IN2010)
Oboe version: master
App name used for testing: OboeTester
(Please try to reproduce the issue using the OboeTester or an Oboe sample.)
 
**Short description**
The sound is stuck when playing in the background, but the foreground is fine.
This case happen when i use 44100 samplerate in opensl. Play fine when using 48k

**Steps to reproduce**
*  Test Output
* API -> OpenSL
* SRate -> 44100
* Start play

**Expected behavior**
The sound is fine when playing in the background.

**Actual behavior**
The sound is stuck when playing in the background

**Device**
OnePlus 8 (OnePlus IN2010)

**Comment by philburk** [comment]
By "stuck" do you mean the sound stopped?
The sound is supposed to stop when playing in the background. There's a
checkbox on the main screen that you can use to enable the background
playback.

Or by stuck do you mean the sound buffer repeated over and over in the
background. That would likely be a problem in the DSP specific to that
device.

Can you capture a very short recording using a second phone?

**Comment by AlphaHans** [comment]
Also, I noticed that my other phone（Oneplus 8T) has no issues after upgrading the android system (from 11 to 12)

I would very much like to know what is the problem causing this phenomenon.

thks

**Comment by xzhan96** [comment]
@philburk could you double check?

**Comment by philburk** [comment]
@AlphaHans - Thanks for reporting this.

I was able to reproduce the same bug on a Pixel 4a 5G running Android 12 SP2A.220505.008!
The glitches sound like buffer underflows caused by the audio thread not being run because it is being given low priority in the background. When I bring it back to the foreground the sound resumes playing properly.

This does not happen with 48000 Hz. It may be related to the buffer sizes, which are calculated by Oboe.

44100 Hz, burst = 960, capacity = 1920
48000 Hz, burst = 96, capacity = 192

https://github.com/google/oboe/blob/9724ec6ab1e2a035a97a6146bdd4fae589e10e6f/src/opensles/AudioStreamOpenSLES.cpp#L186

At 44100, we do not get a LowLatency stream.

**Comment by philburk** [comment]
@AlphaHans - This might be a workaround. In OboeTester, if I set the SRC (Sample rate Converter) quality to Medium then it does not glitch. You can do that in your code:

    builder. setSampleRateConversionQuality([oboe::SampleRateConversionQuality::Medium);

We should still try to fix this.

**Comment by robertwu1** [comment]
I can't repro this on my devices. For all my devices, the sound stops once OboeTester goes to the background. @philburk since you can repro this, I'm assigning the bug to you.

When another activity is moved to the foreground, onPause() is paused. However, we clean up audio for onStop() and onDestroy(). See code for TestAudioActivity.java and image from https://developer.android.com/guide/components/activities/activity-lifecycle below.

~~~
    @Override
    protected void onPause() {
        super.onPause();
    }

    @Override
    protected void onStop() {
        if (!isBackgroundEnabled()) {
            Log.i(TAG, "onStop() called so stop the test =========================");
            onStopTest();
        }
        super.onStop();
    }

    @Override
    protected void onDestroy() {
        if (isBackgroundEnabled()) {
            Log.i(TAG, "onDestroy() called so stop the test =========================");
            onStopTest();
        }
        mAudioState = AUDIO_STATE_CLOSED;
        super.onDestroy();
    }
~~~

![image](https://user-images.githubusercontent.com/85952307/200948443-942d6563-3784-4e63-85f4-039080d0116d.png)

**Comment by philburk** [comment]
I will reproduce this on Pixel 4a 5G and create an internal bug with a bugreport file.

**Comment by xzhan96** [comment]
> I will reproduce this on Pixel 4a 5G and create an internal bug with a bugreport file.

hi @philburk how the issue fixed finally?

**Comment by philburk** [comment]
Tracking in [b/274836642](http://b/274836642) | P1 | OpenSL ES crackles when running in background at 44100 Hz on SP2A

It can be reproduced on R and S but not on UDC.

**Comment by philburk** [comment]
OpenSL ES is also deprecated. So closing as obsolete.

**Comment by philburk** [comment]
If you have this problem then either use AAudio  and/or use the Oboe sample rate converter:

    builder. setSampleRateConversionQuality(oboe::SampleRateConversionQuality::Medium);

**Comment by AlphaHans** [comment]
@philburk Hi philburk.
Thanks for the solution, but I wanted to figure out why this issue was introduced. The above mentioned is because of the problem of thread priority, but it can be solved by adjusting the resampling parameters, why is this?

Our project occasionally ran into noise and stuttering, so I wanted to dive in.

 Looking forward to your reply, thanks again.
