### ISSUE TITLE
[Question] low/minimum latency with USB-C audio interfaces ? 

### ISSUE THREAD

**Issue by the-drunk-coder** [google/oboe#1710]
Hi, 

I've been playing around with the LiveEffect sample to see what is the latency threshold I can achieve.

With the internal sound device, I got down to ~40ms, but when I connect a USB-C interface (a Røde AI-Micro in this case), the latency is significantly higher, with both the AAudio and OpenSL ES APIs. 

Is there a way to lower the latency with the USB-C interface, or is this a systemic issue ? 

My ultimate goal is to create a way to record audio with low-latency software monitoring (for audio devices that don't allow hardware monitoring ... the Røde device doesn't allow stereo monitoring, for example).

Best,
n

**Comment by philburk** [comment]
The latency for USB devices can vary tremendously.
On Pixel and many Qualcomm based devices, the DSP can pass data directly to the DSP.
So there is only a few milliseconds of USB related latency.
If the speakers have latency for speaker protection then USB can have lower latency than the speakers.

But on many devices the data must go through a separate "Legacy USB HAL". We are working to reduce the latency for that data path.

**Comment by the-drunk-coder** [comment]
Ah, that makes sense. I've only been testing it on my cheap Exynos-based Samsung phones. Guess these aren't the best for low-latency then.

Does the Android distribution make a difference as well ? Like, if you say latency can be very low on on a Pixel phone, does it matter whether it runs the stock OS or Lineage ?

**Comment by flamme** [comment]
I believed Exynos-based Samsung is using AOSP USB audio HAL. They don't support passing data directly to DSP.

On AOSP USB audio HAL, the latency will dependent on the USB device capabilities and the playback configuration. If they are matched, they can be in fast path and get lower latency. Otherwise, it will go higher latency.

I don't think we have an existing list tracking devices supporting passing data direct to DSP over USB-C devices.

**Comment by philburk** [comment]
> does it matter whether it runs the stock OS or Lineage ?

I am not familiar with Lineage.
