### ISSUE TITLE
Crash When close playback

### ISSUE THREAD

**Issue by mancity2016** [google/oboe#1773]
crash stack:
1、oboe::FilterAudioStream::onAudioReady(oboe::AudioStream*, void*, int)
/Users/chenweian/code/androidclouddesktop/oboe/src/common/FilterAudioStream.cpp:99
2、std::__ndk1::unique_ptr<oboe::AudioSourceCaller, std::__ndk1::default_delete<oboe::AudioSourceCaller> >::operator bool() const
/Users/chenweian/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/memory:2578

**Comment by philburk** [comment]
You did not fill out the bug report template. So it is hard to help you. Please add more information:

Android version(s):
Android device(s):
Oboe version:
App name used for testing: 
(Please try to reproduce the issue using the OboeTester or an Oboe sample.)
 
**Short description**
(Please only report one bug per Issue. Do not combine multiple bugs.)

**Steps to reproduce**

**Expected behavior**

**Actual behavior**

**Device**

Please list which devices have this bug.
If device specific, and you are on Linux or a Macintosh, connect the device and please share the result for the following script. This gets properties of the device. 

```
for p in \
    ro.product.brand ro.product.manufacturer ro.product.model \
    ro.product.device ro.product.cpu.abi ro.build.description \
    ro.hardware ro.hardware.chipname ro.arch "| grep aaudio";
    do echo "$p = $(adb shell getprop $p)"; done
```

**Any additional context**

If applicable, please attach a few seconds of an uncompressed recording of the sound in a WAV or AIFF file.
