### ISSUE TITLE
Open stream on OpenSL ES should query performance mode

### ISSUE THREAD

**Issue by philburk** [google/oboe#179]
After opening the stream, we should call GetConfiguration(SL_ANDROID_KEY_PERFORMANCE_MODE) to determine the actual final performance mode.

The problem can be seen by using Oboe Tester on Marlin.
Select "Test Output"
Select "OpenSL ES" API.
Select sample rate 44100
Open a Stream:

EXPECT
See "NONE" for performance mode.

ACTUAL
See "LOW_LATENCY", which is not possible for 44100 Hz.

Note in logcat
07-30 04:01:12.778  2993  2993 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 1772

**Comment by ggfan** [comment]
For OSes that does not have performance mode, what would be the expected behavior? For example, on Android M, there is no performance mode, if application asked for performance mode,  after creating the stream and query Oboe for performance mode, do you want to Oboe to return:
- NO performance mode, or
- Yes performance mode ( even Oboe could not ask for underneath layers for it )

If it is later, application does not have to make different code path for different Android OS. Some saving for application and would be benefit of using Oboe.

**Comment by philburk** [comment]
Performance mode is an enum not a boolean. We should return the best matching performance mode. If the version does not support setting performance mode then we should just return _NONE.
