### ISSUE TITLE
SetPitch or SetRate

### ISSUE THREAD

**Issue by alexd555** [google/oboe#182]
I want to add SetPitch or SetRate to audio echo project and I can't understand how to use it.
Look at:
https://www.khronos.org/registry/OpenSL-ES/specs/OpenSL_ES_Specification_1.1.pdf

I understood that these functions are not supported on Android. Why ? I assume that OpenSL ES is dedictated for Android NDK.  Not Like that ?

Could you help ?

**Comment by philburk** [comment]
Android only implements a subset of OpenSL ES. The Android specific implementation is described here:

https://developer.android.com/ndk/guides/audio/opensl/opensl-for-android

I believe that variable rate is supported but not variable pitch.

These are not supported in Oboe because they are not supported in AAudio. They are not in AAudio because they can be implemented at the application level.

If you want to use the variable rate feature of OpenSL ES then you would have to call OpenSL ES directly.

**Comment by alexd555** [comment]
Could you give me an example of rate?
