### ISSUE TITLE
MIDI support

### ISSUE THREAD

**Issue by sinosoidal** [google/oboe#185]
Hi,

Will OBOE support MIDI? 

I would love to see MIDI support with the need to use Java. Right now we depend on two different MIDI API's, one for older devices, another for new devices. We would love to have a central point to connect all our audio and midi callbacks within a C/C++ context. 

Nuno Santos
imaginando.pt

**Comment by dturner** [comment]
At the very least we should release a sample which shows how to get MIDI data from Java->JNI->Native.

**Comment by dturner** [comment]
Closing this due to higher priority things which need doing. 

Here's some resources for anyone looking to add MIDI to their app: 

- Article I wrote on MIDI.org: [Developing MIDI Applications on Android](https://www.midi.org/midi-articles/developing-midi-applications-on-android) 
- Talk I gave at Google I/O 2019: [Sonic Boom! Audio Programming on Android and Chrome](https://www.youtube.com/watch?v=-GaD0RCp-Q0&feature=youtu.be&t=1568). The source code for that talk is here: https://github.com/googlesamples/io19-sonic-boom. Note that the API I'm using is [`AMidi`](https://developer.android.com/ndk/guides/audio/midi) which is only available from Android P onwards. For backwards compatibility you may want to consider using the JVM MIDI API (see the article above for more details).

**Comment by AlejandroHCruz** [comment]
@dturner generally speaking and from a high level standpoint, would the performance with `AMidi` be better than with the JVM MIDI API?

**Comment by dturner** [comment]
You may be able to achieve slightly better latency with `AMidi` because you're able to read from the MIDI message queue inside the audio callback and immediately process that message (for example, to change the pitch of a synthesizer voice) rather than the JVM way of receiving a callback when a new MIDI message is ready, then having to copy that message down into C++ land over JNI. 

In real world terms, there's probably not much in it though since both methods are very low latency anyway (approx 1-3ms for the MIDI message to enter the message queue)
