### ISSUE TITLE
ANR happens if plugin headset while do recording

### ISSUE THREAD

**Issue by xzhan96** [google/oboe#1947]
Android version(s): 13
Android device(s): 	
xiaomi 2203121c
Oboe version: latest source code
App name used for testing: apk built by latest source code
(Please try to reproduce the issue using the OboeTester or an Oboe sample.)
 
**Short description**
(Please only report one bug per Issue. Do not combine multiple bugs.)

**Steps to reproduce**
- start record case: one of below case
![img_v3_0265_3c01d00f-263e-44f5-a3b1-cfe147e0587g](https://github.com/google/oboe/assets/13726257/10eb245e-b964-4f0e-8aa4-b49dc2f1e115)
- plugin a headset 

**Expected behavior**
recording works well

**Actual behavior**
ANR happens

[logcat.log](https://github.com/google/oboe/files/13683533/logcat.log)

**Comment by xzhan96** [comment]
[](url)

**Comment by xzhan96** [comment]
[bugreport-others.zip](https://github.com/google/oboe/files/13683564/bugreport-others.zip)
[bugreport-thor-TKQ1.220829.002-2023-12-15-15-55-13.txt.zip](https://github.com/google/oboe/files/13683565/bugreport-thor-TKQ1.220829.002-2023-12-15-15-55-13.txt.zip)

**Comment by xzhan96** [comment]
It seems ANR happens here, please see my attached logcat file for more details:
![img_v3_0265_1cd75f28-5534-499e-966a-d0b40d2fa45g](https://github.com/google/oboe/assets/13726257/a30dbea9-8f1e-4a42-b446-2002692c32d3)

**Comment by philburk** [comment]
The logcat.log shows a SIGSEGV

'''
12-15 15:39:15.159  7124 15030 F libc    : Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7791afd000 in tid 15030 (AudioRecord), pid 7124 (leer.oboetester)
12-15 15:39:15.392 15041 15041 F DEBUG   : Cmdline: com.mobileer.oboetester
12-15 15:39:15.392 15041 15041 F DEBUG   : pid: 7124, tid: 15030, name: AudioRecord  >>> com.mobileer.oboetester <<<
12-15 15:39:15.412  2530 15045 W ActivityTaskManager:   Force finishing activity com.mobileer.oboetester/.TestInputActivity
'''

Also it looks like OboeTester is not using the shared_ptr!

'''
12-15 15:39:24.620  7125  7125 D OboeTester: OboeAudioStream_openNative: sampleRate = 0
12-15 15:39:24.620  7125  7125 W OboeAudio: Passing AudioStream pointer deprecated, Use openStream(std::shared_ptr<oboe::AudioStream> &stream) instead.
12-15 15:39:24.620  7125  7125 I OboeAudio: openStream() INPUT -------- OboeVersion1.8.0 --------
'''

**Comment by philburk** [comment]
I cannot reproduce this on a Pixel 7 Pro running V.

bugreport-thor-TKQ1.220829.002-2023-12-15-15-55-13.txt.zip
shows many instances of the audioserver dieing!

12-15 14:46:15:442 onAudioServerDied() audioserver started
12-15 14:46:15:550 after audioserver restart: initStreamVolume succeeded
12-15 14:49:47:716 onAudioServerDied() audioserver died
12-15 14:49:48:218 onAudioServerDied() audioserver started
12-15 14:49:49:980 after audioserver restart: initStreamVolume succeeded
12-15 14:51:59:454 onAudioServerDied() audioserver started
12-15 14:51:59:578 after audioserver restart: initStreamVolume succeeded
12-15 15:23:53:818 onAudioServerDied() audioserver started
12-15 15:23:53:995 after audioserver restart: initStreamVolume succeeded
12-15 15:25:18:509 onAudioServerDied() audioserver started
12-15 15:25:18:634 after audioserver restart: initStreamVolume succeeded
12-15 15:28:22:082 onAudioServerDied() audioserver died
12-15 15:28:22:586 onAudioServerDied() audioserver started
12-15 15:28:23:704 after audioserver restart: initStreamVolume succeeded
12-15 15:39:59:522 onAudioServerDied() audioserver died
12-15 15:40:00:023 onAudioServerDied() audioserver started
12-15 15:40:00:637 after audioserver restart: initStreamVolume succeeded
12-15 15:41:28:098 onAudioServerDied() audioserver died
12-15 15:41:28:600 onAudioServerDied() audioserver started
12-15 15:41:29:277 after audioserver restart: initStreamVolume succeeded

That can cause an ANR if it takes a long time for the audioservice to recover.
This is often caused by a crash in the audio HAL.

**Comment by philburk** [comment]
Basic default INPUT stream is opened here:

12-15 15:39:14.588 10074  7124  7124 I OboeAudio: openStream() INPUT -------- OboeVersion1.8.0 --------
12-15 15:39:14.589 10074  7124  7124 I AAudio  : AAudioStreamBuilder_openStream() called ----------------------------------------
12-15 15:39:14.589 10074  7124  7124 I AudioStreamBuilder: rate   =      0, channels  = 0, channelMask = 0, format   = 0, sharing = EX, dir = INPUT
12-15 15:39:14.589 10074  7124  7124 I AudioStreamBuilder: device =      0, sessionId = -1, perfMode = 12, callback: ON with frames = 0
12-15 15:39:14.589 10074  7124  7124 I AudioStreamBuilder: usage  =      0, contentType = 0, inputPreset = 6, allowedCapturePolicy = 0
12-15 15:39:14.589 10074  7124  7124 I AudioStreamBuilder: privacy sensitive = false, opPackageName = (null), attributionTag = (null)

A legacy FAST CAPTURE is created:

12-15 15:39:14.617 10074  7124  7124 I AudioRecord: createRecord_l(3014756): AUDIO_INPUT_FLAG_FAST successful; frameCount 0 -> 4096


12-15 15:39:15.003 10074  7124  7124 D AAudio  : AAudioStream_requestStart(s#1) called --------------
12-15 15:39:15.003 10074  7124  7124 D AAudioStream: setState(s#1) from 2 to 3

12-15 15:39:15.028  1041 12243 15037 D PAL: Stream: create: 300: Exit stream 0xb400007756235000K create successful

Some HAL errors:

12-15 15:39:15.040  1000  1310  1310 E ACDB    : AcdbCmdGetGraphAlias:4153 Error[19]: Graph Alias chunk data does not exist. Is it enabled?.
12-15 15:39:15.040  1000  1310  1310 E gsl     : gsl_get_graph_alias:2182 acdb get graph alias failed 19, len 255
12-15 15:39:15.040  1000  1310  1310 D AGM: graph: print_graph_alias: 2201 gsl_get_graph_alias failed: ret = 19


12-15 15:39:15.043  1000  1310  1310 E ACDB    : AcdbCmdGetProcSubgraphCalDataPersist:8408 Error[19]: No calibration found
12-15 15:39:15.043  1000  1310  1310 E ACDB    : AcdbCmdGetProcSubgraphCalDataPersist:8408 Error[19]: No calibration found

Followed shortly after by the SIGSEGV

12-15 15:39:15.159 10074  7124 15030 F libc    : Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7791afd000 in tid 15030 (AudioRecord), pid 7124 (leer.oboetester)

12-15 15:39:15.392 10074 15041 15041 F DEBUG   : backtrace:
12-15 15:39:15.392 10074 15041 15041 F DEBUG   :       #00 pc 000000000006b494  /system/lib64/libaudioclient.so (android::AudioRecord::isLongTimeZeroData(void const*, int)+120) (BuildId: 6941810c194e4817ae776541e5e0fe99)
12-15 15:39:15.392 10074 15041 15041 F DEBUG   :       #01 pc 000000000006a90c  /system/lib64/libaudioclient.so (android::AudioRecord::processAudioBuffer()+1752) (BuildId: 6941810c194e4817ae776541e5e0fe99)
12-15 15:39:15.392 10074 15041 15041 F DEBUG   :       #02 pc 0000000000069f3c  /system/lib64/libaudioclient.so (android::AudioRecord::AudioRecordThread::threadLoop()+288) (BuildId: 6941810c194e4817ae776541e5e0fe99)


12-15 15:39:59:522 onAudioServerDied() audioserver died

**Comment by philburk** [comment]
@xzhan96 - Thanks for reporting this. I need some more information.

How often does the ANR happen? Every time? Once?

If it happens every time, please reboot the phone, reproduce the ANR, then take a bugreport immediately.
That will give us a very clean bugreport.

If device specific, and you are on Linux or a Macintosh, connect the device and please share the result for the following script. This gets properties of the device. 

```
for p in \
    ro.product.brand ro.product.manufacturer ro.product.model \
    ro.product.device ro.product.cpu.abi ro.build.description \
    ro.hardware ro.hardware.chipname ro.arch "| grep aaudio";
    do echo "$p = $(adb shell getprop $p)"; done
```

**Comment by xzhan96** [comment]
> @xzhan96 - Thanks for reporting this. I need some more information.
> 
> How often does the ANR happen? Every time? Once?
> 
> If it happens every time, please reboot the phone, reproduce the ANR, then take a bugreport immediately. That will give us a very clean bugreport.
> 
> If device specific, and you are on Linux or a Macintosh, connect the device and please share the result for the following script. This gets properties of the device.
> 
> ```
> for p in \
>     ro.product.brand ro.product.manufacturer ro.product.model \
>     ro.product.device ro.product.cpu.abi ro.build.description \
>     ro.hardware ro.hardware.chipname ro.arch "| grep aaudio";
>     do echo "$p = $(adb shell getprop $p)"; done
> ```

thanks @philburk , I have confirmed this is a XiaoMi ROM's bug, they will fix it recently.

**Comment by osoftware** [comment]
@xzhan96 can you provide the version number where it was fixed? I'm still receiving these errors in year 2025.

**Comment by osoftware** [comment]
@xzhan96 This is still happening in 2026. Please reopen the issue.

**Comment by philburk** [comment]
The bug was found to be in XiaoMi's ROM in 2023. It should be fixed by now.

@osoftware  - Are you also using a Xiaomi device?

Note that there can be multiple causes for crashes, particularly when plugging in headphones.
It is likely that you are hitting a different bug.
Are you seeing the crash in OboeTester or your own app?

Please open a new bug with the details of your crash. A stack dump would be great. Also more information about your device would be helpful.  You can reference this bug from your bug if you think they are related.

See also:  https://github.com/google/oboe/wiki/TechNote_HowToAvoidCrashes
