### ISSUE TITLE
Question: How to find out if Oboe is performing Sample Rate Conversion?

### ISSUE THREAD

**Issue by JimG777** [google/oboe#2054]
When building a stream, for example:
```
    oboe::AudioStreamBuilder builder;
    builder.setSampleRate(48000);
    builder.setFormatConversionAllowed(true);
    builder.setSampleRateConversionQuality(oboe::SampleRateConversionQuality::Medium);
    oboe::Result result = builder.openStream(my_stream);
```

If the device's native sample rate is not 48000, I expect Oboe will perform the conversion. Is there a way to know if the conversion is happening or not? The goal is to add the information to log output so we know about it when debugging user issues.

Thank you!

**Comment by philburk** [comment]
Oboe can do three types of conversion: format, channel count, and sample rate.
When it doing this conversion it creates a FilterAudioStream that acts as a wrapper for the regular AudioStream.h.
When you write to the FilterAudioStream it does the conversion and then calls the underlying regular stream.
If the conversion is not necessary, because, for example, the underlying sample rate is also 48000, then Oboe will not use a FilterAudioAudio stream and just give you the regular underlying stream.

So you could call stream->getUnderlyingStream(). If it returns null then there is no conversion by Oboe.
Otherwise it means you actually have a FilterAudioStream that does conversion.

Note that this technique should ONLY be used for debugging. See the docs:
https://google.github.io/oboe/classoboe_1_1_audio_stream.html#a8b9c04ff659ccbcfcf6bc08a1a01a69c

Maybe we should add an AudioStream method:

    bool isOboeConversionActive() { return (getUnderlyingStream != nullptr); }

**Comment by JimG777** [comment]
Hi Phil, thanks for the explanation and information.

> Maybe we should add an AudioStream method

+1 to that, it would be informative I think, since we would prefer this in production. But not sure if it would overly complicate the API, your call! But I'll close this issue.
