### ISSUE TITLE
Oboe is using indexed channel masks for OpenSL ES

### ISSUE THREAD

**Issue by philburk** [google/oboe#206]
At:
https://github.com/google/oboe/blob/52a5eba54162b03526c197db071e5d3f88c01352/src/opensles/AudioStreamOpenSLES.cpp#L61

There may be an open related bug in Android:
b/35749641 | Using indexed channel masks results in fastmixer being denied

So maybe we should not be doing that. But it seems like we do get a FAST track.

We need to sort out what is really happening and do the right thing for the right versions.

**Comment by dturner** [comment]
Look at b/35749641 and determine whether we need to conditionally use indexed channel masks on specific android versions

**Comment by dturner** [comment]
Oboe is currently only using indexed channel counts when the channel count is 3, 5 or 7. See: https://github.com/google/oboe/blob/63fef12697ec0c81c68d705cdeb6551ea2731c1a/src/opensles/AudioOutputStreamOpenSLES.cpp#L50

We could change it so that indexed channel masks would always be used but this would be a bad idea because of b/35749641.

The crux of the issue seems to be that a fast track is only granted if the requested channel mask matches the channel mask of the audio device. So if you request a non positional channel mask (e.g. b11 = 2 channels) and the audio device only has a positional (e.g. STEREO) mask then they are deemed not to match and the fast track is denied. 

Some questions (mostly for my own record): 

- Is it possible to obtain the supported channel masks for a given audio device? 
Answer: Yes for input devices (see AudioDeviceEnum test app), probably no for output devices currently (see b/35800446)

- What is the behaviour we actually want? 
Positional and indexed channel masks serve 2 different purposes. Positional is generally for watching movies (think rear speakers) and indexed is for music studios and DJing (where you want to route different channels of audio to different devices). 

If a device offers up a single supported positional channel mask (e.g. Stereo) then we should be able to map it to a corresponding indexed channel mask (e.g. b11 | positional_bit), and vice versa. 

Apps probably just want to know what the max channel count for a given audio device and then supply audio frames containing samples for each channel, without being concerned about the index or position of those channels - is this a correct assumption?

**Comment by dturner** [comment]
Removing from v1.0 because the current behaviour works for the most popular channel counts.

**Comment by philburk** [comment]
Great analysis Don!
Stereo is easy because the positional mask is 0x00000003 and the indexed mask is 0x80000003.
For 3 channels we can add the CENTER channel and get b111.
The "LOW_FREQUENCY" channel at b1000 complicates things. Should we skip that for the 5 channel ?

> Apps probably just want to know what the max channel count for a given audio device and 
> then supply audio frames containing samples for each channel, without being concerned 
> about the index or position of those channels - is this a correct assumption?

For studio apps, yes. Video apps care more about speaker placement so they can route surround sound correctly.

It is ironic that indexed masks do not get the FAST track because they are more likely to want low latency.

I agree about punting for 1.0.  I think a real fix for this may involve:

1. fixing  b/35749641
2. adding a positional setChannelMask() API to AAudio and Oboe for movie apps
3. if app requests LowLatency then do not use indexed masks before the fix for opensles
4. if app requests None then OK to use indexed masks

We should also run some tests to see what channels actually get used when we hook up an 8 channel USB device.

**Comment by dturner** [comment]
I'm going to close this as "stale" because I haven't heard any reports of developers running into issues here. If you have this issue please reopen.

**Comment by philburk** [comment]
There is still some work we can do on this when we get time.

**Comment by philburk** [comment]
Closing again for lack of interest.
