### ISSUE TITLE
Invalid RIFF header chunksize and data chunksize size in recorded wav file

### ISSUE THREAD

**Issue by prabint** [google/oboe#2108]
Android version(s): any
Android device(s): any
Oboe version: 1.9.0
App name used for testing: OboeTester
 
**Short description**
I am using `NativeAudioContext.cpp#saveWaveFile()` to record and save wav audio file. The recorded file cannot not be played back using Android's `MediaPlayer` because data and RIFF chunksize placeholder values `INT32_MAX`, assigned in `writeDataChunkHeader()` and `writeRiffHeader()`, are not updated after recording is completed. I was hoping `writer.close();` would do it, but that method is empty.

I was able to get the wav file playing by replacing `writeIntLittle(INT32_MAX)` in `writeRiffHeader()` and `writeDataChunkHeader()` with variables whose values are set once recording is stopped:
```
auto dataSize = mRecording->getSizeInFrames() * channelCount * bytesPerSample;
writer.setRiffChunkSize(dataSize + 36);
writer.setDataSize(dataSize);
```

**Steps to reproduce**
1. Open  OboeTester app and click "RECORD AND PLAY" -> RECORD -> STOP -> SHARE (to create wav file)
2. Open the wav file using https://hexed.it and observe two instances of `FF FF FF 7F`
3. Or, try playing this wav file using MediaPlayer or YTMusic and observe errors

**Comment by philburk** [comment]
@prabint - Thanks for reporting this. It is a fairly common technique to put the DATA chunk at the end of the file and to set the RIFF and DATA chunk sizes to INt32_MAX. Sometimes this cannot be avoided because the output WAV file is being written to a stream and we do not know the final size. And when we finally know the size we sometimes cannot rewind or update the file.

Because of this, many apps just clip the chunk sizes against the file size. Audacity can handle this fine.
But MediaPlayer and YTM apparently do not.  We should modify MediaPlayer and YTM to handle those invalid but common WAV files.

AND you have shown that we can probably write the correct chunk sizes in OboeTester. So we should do that too.
