### ISSUE TITLE
setDeviceId() does nothing for OpenSL ES

### ISSUE THREAD

**Issue by philburk** [google/oboe#228]
Oboe Tester, Test Input
Select Open SL ES
select an input device that does not work with AAudio, eg "FM Radio" an a device with a radio
Open, Start

EXPECT: no audio
ACTUAL: See audio signal, just like with mic, input device is ignored.

Maybe need isDeviceIdSupported()

**Comment by philburk** [comment]
getDeviceId()  always returns 0.

**Comment by philburk** [comment]
There are several things that OpenSL ES does not support, including:

- deviceId
- timestamp
- xrunCount
- some attributes

Maybe we need a more general solution.

**Comment by SchmadenSchmuki** [comment]
Hello
Had the same problem, can't choose audiodevice for input or output because select device is not set and deviceId is always 0.
Interesting thing was, when I plugged in my headset or unplugged it, there was an automatic response to that. In- and output switched to the headset when plugging it and back to the device when unplugging. Also the stream wasn't disconnected, it just kept working (when selecting AAudio as AudioApi it usually disconnects).

Tested it with Nexua 5X, Android 8.1.

So is there any other way to select the audio device when OpenSL ES is selected?
Does it happen on all android devices?

**Comment by philburk** [comment]
OpenSL ES automatically routes sound between devices. But that causes a lot of problems. For example if you switch to Bluetooth and back then you are stuck with high latency and the app doesn't know it. So in AAudio we disconnect the stream when the device changes.

**Comment by atneya** [comment]
Do we have documentation that `setDeviceId()` does not work in OpenSLES?

**Comment by philburk** [comment]
setDeviceId() is documented.
https://github.com/google/oboe/blob/77ea1882f072d0a607247b722e7cc985a1edb6d8/include/oboe/AudioStreamBuilder.h#L293

But also xRunCount is not supported, etcetera

**Comment by dturner** [comment]
The docs are pretty clear here. Closing. https://google.github.io/oboe/reference/classoboe_1_1_audio_stream_builder.html#af36ddcd00686a9e1de661bdac0685a8e
