### ISSUE TITLE
question: oboe and ndk

### ISSUE THREAD

**Issue by wsc1** [google/oboe#229]
Hi,
I was wondering if there are plans to make oboe part of the Android ndk?

I see the instructions for use say to download Android ndk separately, but there are license headers which state "the android open source project" as the copyright owner.  Naturally it seems there would be some interest.

Sorry if its a dumb question, I'm new to android development.

**Comment by dturner** [comment]
Hi William, 

Not a dumb question. There are no plans to bundle Oboe with the NDK. In fact, the opposite. We do not want to ship with the NDK because then we'd be tied to its release cycle. By keeping Oboe independent we can fix bugs and release new features quicker. 

All open source projects released in relation to Android use the AOSP license. More info here: https://source.android.com/setup/start/licenses

Hope that answers your questions. 

Don

**Comment by dturner** [comment]
Feel free to reopen if you have more questions.
