### ISSUE TITLE
Crackle sound on Galaxy S9 (OpenSLES)

### ISSUE THREAD

**Issue by pbodilis** [google/oboe#286]
It is not clear as to what may be the root cause of the problem, but maybe someone around here can give me the solution...

I use oboe in a VoIP / push-to-talk application. When I press the "push" button, I create an oboe Stream, while upon release, I destroy it. I cannot use pause or requestPause as those are not available with OpenSL. When I press the button, there is no output streams.

I have a Galaxy S9:
* Android 8.0
* Kernel 4.9.59-14479316-QB20373867 #1 SMP PREEMPT Mon Oct 29 11:52:44 KST 2018
* Build number R16NWE G960FXXS2BRJ6

Using the audio manager properties PROPERTY_OUTPUT_SAMPLE_RATE and PROPERTY_OUTPUT_FRAMES_PER_BUFFER,  I have set opensl values to
* oboe::DefaultStreamValues::SampleRate:  48000
* oboe::DefaultStreamValues::FramesPerBurst: 192

I'm using oboe with a callback:
`

    oboe::DataCallbackResult SwAudioImplOboeRecorderCallback::onAudioReady(oboe::AudioStream *oboeStream, void *audioData, int32_t numFrames) {
        if (!mCapt->running) {
            return oboe::DataCallbackResult::Stop;
        }
        //ssize_t res =
        sw_circular_buffer_write(mCapt->circular_buffer, (uint8_t *)audioData, numFrames * oboeStream->getBytesPerSample());
    
        return oboe::DataCallbackResult::Continue;
    }

`

And my code creating the stream:

`

        builder.setDirection(oboe::Direction::Input);
        builder.setPerformanceMode(oboe::PerformanceMode::LowLatency);
        builder.setSharingMode(oboe::SharingMode::Shared);
        builder.setSampleRate(fb->a.sample_rate); // 48000
        builder.setChannelCount(fb->a.number_of_channels); // 1
        builder.setBufferCapacityInFrames(buffer_capacity); // 
        builder.setFormat(oboe::AudioFormat::I16);
        builder.setUsage(oboe::Usage::VoiceCommunication);
        builder.setContentType(oboe::ContentType::Speech);

        builder.setInputPreset(oboe::InputPreset::Generic);

        builder.setCallback(capt->oboe_callback);

        oboe::AudioStream *oboe_stream = NULL;
        oboe::Result err = builder.openStream(&oboe_stream);
        if (err != oboe::Result::OK) {
            LOGE("Failed to create stream: %d (%s)", err, oboe::convertToText(err));
            return read_error;
        }

        LOGI("Successfully created oboe recorder stream: '%s' (deviceId: %d, usage: %d, contentType: %d, inputPreset: %d, bufferSize: %d, sampleRate: %d)",
             oboe::convertToText(oboe_stream->getAudioApi()),
             oboe_stream->getDeviceId(),
             oboe_stream->getUsage(),
             oboe_stream->getContentType(),
             oboe_stream->getInputPreset(),
             oboe_stream->getBufferCapacityInFrames(),
             oboe_stream->getSampleRate()
        );
`

I get the log:
`Successfully created oboe recorder stream: 'OpenSLES' (deviceId: 0, usage: 2, contentType: 1, inputPreset: 1, bufferSize: 384, sampleRate: 48000)`

This code works perfectly on various devices, and even on my S9 it works most of the time. but there some times where the sound is crackled. What do I do wrong?

**Comment by mregnauld** [comment]
I have a similar problem when I test the hello-oboe example on a Galaxy S7, sometimes, the sound is also randomly crackled, for a very short period of time when it happens (like a few milliseconds).

It really sounds like there is an underrun, so I tried using the `AudioStreamBuffered::setBufferSizeInFrames()` function to get a bigger buffer. This fix worked like a charm on a device with Android API 27, but unfortunately, it doesn't work on my Galaxy S7 that has API 23 (using OpenSLES, then), since this function is only supported when we are not using a callback (only for OpenSLES).

For those reasons, I think that this problem has to be addressed as soon as possible.

**Comment by philburk** [comment]
A quick note as I read the Issue:
>     sw_circular_buffer_write(mCapt->circular_buffer, (uint8_t *)audioData,
>               numFrames * oboeStream->getBytesPerSample());

That should probably be getBytesPer**Frame**() not getBytesPer**Sample**().
For mono they will be the same because a frame has one sample. But for stereo it matters.
I know this is not relevant to the crackle.
More to follow...

**Comment by pbodilis** [comment]
> A quick note as I read the Issue:
> 
> > ```
> > sw_circular_buffer_write(mCapt->circular_buffer, (uint8_t *)audioData,
> >           numFrames * oboeStream->getBytesPerSample());
> > ```
> 
> That should probably be getBytesPer**Frame**() not getBytesPer**Sample**().
> For mono they will be the same because a frame has one sample. But for stereo it matters.
> I know this is not relevant to the crackle.
> More to follow...

You're probably right, I'll change my code.

Regarding the crackling sound, can this be related to other players in the app (there's a mediaplayer in the java layer)? Audiomanager's mode? A bug in OpenSL? I read somewhere (can't remember where) that this could be a resampling issue?

I guess I'll have to stick to AudioRecord though JNI for now, until AAudio is more available.

**Comment by philburk** [comment]
The crackling, or "glitches", occurs when something prevents the application from servicing the buffer. For input, this can cause the buffer to overflow. For output, this can cause the buffer to underflow.

We are doing several things to help reduce glitching. We are working with phone manufacturers to improve the drivers and reduce the source of glitches.  We also created a new API called AAudio that is designed with high performance in mind. In AAudio you can increase the size of the buffer dynamically. That can help prevent glitches because it takes more time to overflow.

We cannot fix old versions of the OS. All we can do is make improvements and then wait for those change to spread to more and more phones.

We can also try to optimize the code for each platform. Oboe helps us do that. And we can optimize applications to make the best use of the platform.

Full duplex audio is tricky. In general, you want the input buffers to run near empty and the output buffers to run near full. Then if the application is preempted, the input buffer can fill and the output can drain without causing a glitch. If both input and output are full or empty then you have no safety margin when there is a preemption. One of them will glitch.

> I guess I'll have to stick to AudioRecord though JNI for now,

If AudioRecord is working better than it maybe is allowing you to create a larger input buffer.

**Comment by pbodilis** [comment]
Thanks again for your answer.

I'm not fully convinced it's about the buffer size:
* in the code above, I call SetBufferSize with value buffer_capacity set to 2880 (so, 60ms of sound with a 48000Hz sample rate, mono).
* AudioRecord is created using the value returned by AudioRecord.getMinBufferSize(48000, AudioFormat.CHANNEL_IN_MONO, AudioFormat.ENCODING_PCM_16BIT), which is 3840 bytes on my phone, so 1920 frames (40ms). 

Am I misusing setBufferCapacityInFrames? or should I omit it?


For test purposes, I've added logs in the callback and the reading thread, and coudn't detect any underrun nor overrun. There's no gap in the sound, It sounds like it is muffled with statics(?).

Can't wait for AAudio to be more available!

**Comment by philburk** [comment]
> I'm not fully convinced it's about the buffer size
>  builder.setBufferCapacityInFrames(buffer_capacity);

In Oboe, that is a request for capacity.  In AAudio you will get at least that much. With OpenSL ES you may get much less. Try calling stream->getBufferCapacityInFrames() for the final capacity. It may only be (2*192). The docs say
    "The final stream capacity may differ, but will probably be at least this big."

I will reword that.  https://github.com/google/oboe/pull/291

> Am I misusing setBufferCapacityInFrames? or should I omit it?

Keep it. It helps with AAudio but may be ignored with OpenSL ES.

>  I've added logs in the callback and the reading thread,

Logs that print from a real-time audio thread can cause glitches. So be careful with that.

> There's no gap in the sound, It sounds like it is muffled with statics(?).

Muffled?! Is it like that on all devices or just some? Normally with glitches the audio will sound fine and then there will be some very short little pops that seem kind of random.

**Comment by philburk** [comment]
Closing sue to inactivity. Please reopen if needed.

**Comment by gohome** [comment]
I have experienced the similar issue with Android native audio API ( either OpenSLES or AAudio ) on some Samsung devices ( S8, S9 and S8+ ) even with the sample apps. The workaround I have found is either changing the performance mode to SL_ANDROID_PERFORMANCE_LATENCY on OpenSLES  or AAUDIO_PERFORMANCE_MODE_NONE on AAudio. My assumption is the hardware driver on those devices didn't support low latency well and requires some HW post processing.
