### ISSUE TITLE
Will there be a stable release for Oboe?

### ISSUE THREAD

**Issue by Matze1** [google/oboe#303]
Hello,
since 2nd of October Oboe is at version 1.0 but as the master branch is modified frequently I am curious if a stable release is planned?

**Comment by dturner** [comment]
Great question. Oboe on master is stable currently since there have been no breaking API changes, however, we will create a stable branch shortly which won't change except for bugfixes.

**Comment by dturner** [comment]
Thanks for asking this, your issue prompted me to do a few things: 

1) Update the releases page to include the 1.0.0 and 1.1.0 releases: https://github.com/google/oboe/releases
2) Create a 1.1-stable branch which will only have bug fixes, no API changes
3) Make this the default branch for Oboe so that new users will always get a stable branch

Hopefully that works for you - let me know if you have any suggestions for our release process.
