### ISSUE TITLE
Is it a safe assumption to make that calling `setChannelCount(1)` will result in just the main microphone being used? 

### ISSUE THREAD

**Issue by Nimitz14** [google/oboe#310]

**Comment by philburk** [comment]
It depends on many factors including the InputPreset, StreamType, Usage and whether the SpeakerPhone is enabled. If you use InputPreset::Camcorder, for example, then you will probably get the back mic.

It also depends on the device and what mics the hardware has. Some phones only have one mic. And it depends on whether a headset with a mic is plugged in or a Bluetooth headset is connected.

And it depends on how the OEM has configured the audio policy manager.

And some devices may take the signal from multiple mics and combine them in order to reduce noise.

This routing of signals is one of the most complex parts of the Android Audio system.

So the only thing you can safely assume is that the input data will have a single channel.

**Comment by Nimitz14** [comment]
So is there a way to manually specify to use just the main microphone? You mention `InputPreset`, which is not mentioned in the full oboe guide by the way, can one use that maybe to select the main microphone somehow?

[All I want is what already exists in the Java interface via `setAudioSource()`](https://developer.android.com/guide/topics/media/mediarecorder#audiocapture):

> Set the audio source using setAudioSource(). You'll probably use MIC

> Note: Most of the audio sources (including DEFAULT) apply processing to the audio signal. To record raw audio select UNPROCESSED. Some devices do not support unprocessed input. Call AudioManager.getProperty(AudioManager.PROPERTY_SUPPORT_AUDIO_SOURCE_UNPROCESSED) first to verify it's available. If it is not, try using VOICE_RECOGNITION instead, which does not employ AGC or noise suppression. You can use UNPROCESSED as an audio source even when the property is not supported, but there is no guarantee whether the signal will be unprocessed or not in that case.

**Comment by philburk** [comment]
The closest thing to what you want is:   AudioStreamBuilder::setInputPreset()

    https://github.com/google/oboe/blob/master/include/oboe/AudioStreamBuilder.h#L238

You can also query the set of audio devices and then pass the device id for a specific mic using
    AudioStreamBuilder::setDeviceId()

Note that there are autodocs in your repository at:
       oboe/docs/reference/index.html

**Comment by Nimitz14** [comment]
Thank you!
