### ISSUE TITLE
error: no member named 'at_quick_exit' in the global namespace

### ISSUE THREAD

**Issue by dturner** [google/oboe#317]
When I attempt to run `tests/run_tests.sh` the build fails with the following error: 

    error: no member named 'at_quick_exit' in the global namespace

Checking Android Studio (3.4 canary 8)-> SDK manager->Tools it shows "NDK (side by side) as Not Installed, which is strange because the ~/Library/Android/sdk/ndk-bundle exists. 

Attempting to reinstall the NDK.

**Comment by dturner** [comment]
I have no real idea what was causing this but uninstalling Android Studio 3.4 and installing the latest stable version (3.2), then reinstalling the NDK fixed the issue.

**Comment by chussong** [comment]
This issue seems to have made it into the release version of Android Studio 3.3, which is now the stable one. I'm compiling on Ubuntu 18.10, and reinstalled Android Studio and the NDK before making any changes to oboe.

I believe it's caused by adding an extra include directory, which makes Clang find the wrong versions of the C standard library files. I was able to fix it by commenting out line 18 of tests/CMakeLists.txt, but I'm reluctant to submit a pull request to that effect since I don't know enough about your code base to be confident that this is the correct change to make.

I also had to set the environment variable ANDROID_HOME to get CMake to compile without errors; of course, if ANDROID_HOME is set, ANDROID_NDK is likely just $(ANDROID_HOME)/ndk-bundle, so perhaps these could be combined.

**Comment by dturner** [comment]
Thanks for your comment, just ran into this again. I have submitted a PR which removes the explicit include path for the Android headers. My guess is that the NDK version of GoogleTest specifies the correct include paths so we don't need to worry about it, and indeed shouldn't, because it breaks the build.
