### ISSUE TITLE
AAudio: Connecting headphones does not trigger any event. S9 Exynos 9.0

### ISSUE THREAD

**Issue by Themaister** [google/oboe#381]
The documentation says that the error callbacks should be called when the "primary device" changes, however, it does not when attaching headphones. It does trigger when detaching headphones though ...

**Comment by philburk** [comment]
We have seen this behavior on early versions of P release for AAudio on Pixel.

What device and Android version are you seeing this on?
Are you using OpenSL ES or AAudio?
Are the headphones using a 3.5 mm jack or USB-C?
Is it intermittent or consistent?

OpenSL ES will automatically switch the audio between headset and speakers. But it also can change the latency and disrupts the audio streams, which is why we try to force a disconnect in AAudio.

**Comment by Themaister** [comment]
- Samsung Galaxy S9 Exynos, Android 9.0.
- AAudio.
- 3.5mm jack.
- Consistent.

OpenSL ES works fine.

**Comment by svenoaks** [comment]
This happens on same device for me too. Along with #380.

**Comment by dturner** [comment]
Possibly related internal bug b/111711159

**Comment by philburk** [comment]
This is not an Oboe bug. The problem is in the AudioPolicyManager.
We are documenting the issue and a workaround here:

https://github.com/google/oboe/blob/master/docs/notes/disconnect.md
