### ISSUE TITLE
Adding Oboe to existing project, can't find certain header/cpp files

### ISSUE THREAD

**Issue by sdenheyer** [google/oboe#404]
Hi - I'm new to native & oboe - I'm trying to get oboe running in my project, and not having much luck.

I've created my CMakeLists.txt file acc'ding to the "Getting Started" instructions, everything seems to build and link without errors, directories under "app/cpp/oboe" are populated with all the right folders and files.

But, "#include <oboe/Oboe.h>" complains about not being able to find directory "oboe", and auto-completing methods in oboe:: finds everything in "aaudio" and "opensles", but nothing from "common" - which includes the stream builder.  It acts as if the "common" and "fifo" directories don't exist.

I've tried clean rebuilds, invalidating caches, modifying my CMakeLists, I've checked CMakeLists under oboe for possible errors, and I tried starting a new native project and bringing Oboe into that.  As a long shot, I tried "#include Oboe.h" using an absolute path to the file, which did work, but I think only solves one problem among many.

I'm using Android Studio 3.3.2, NDK 19.1, gradle 3.3.2.

Thank you.

**Comment by sdenheyer** [comment]
A quick update on this - I managed to get everything working by copying the necessary oboe files straight into my apps cpp directory and writing my own (basic) CMakeLists.  Everything seems to work right now - up to compiling and running on a phone.

If you have any suggestions on how to get it working the "right" way, let me know.  Cheers.

**Comment by dturner** [comment]
Sorry to hear you had problems with this. I've also had this a number of time with Android Studio not indexing Oboe's symbols. 

There's a "hidden" cache folder in Android Studio. It's in ~/Library/Caches/AndroidStudio<version>. If you're struggling with the indexer not finding objects, try closing AS and deleting the contents of this folder and reopening. 

I will add this to the list of FAQs. Please reopen this if you still have issues - we absolutely want to make Oboe as simple to install and use as possible.

**Comment by tupinator** [comment]
Hi! I'm having the same issue as sdenheyer. I'm on Windows 10 so there's no ~/Library/Caches/AndroidStudio that I can clear out. I've followed the Getting Started guide perfectly and I'm pretty sure that my project does have access to oboe since when I include <oboe/Oboe.h> in native-lib.cpp it allows me to use the functions in the oboe namespace but when I create other header files such as AudioEngine.h in the same folder it says 'oboe/Oboe.h' file not found.  I'd really appreciate your help as my whole project is supposed to fully depend on Oboe.

I'm using Gradle model version=6.5, NDK version=21.1.6352462 and Android Studio version 4.1.
