### ISSUE TITLE
How to amplify the output in LiveEffect Sample?

### ISSUE THREAD

**Issue by j4zib** [google/oboe#424]
I tried amplifying the output like this:
```
auto *outputData = static_cast<float *>(audioData);
    for (int i = 0; i < numFrames*channelCount; ++i){
        outputData[i] = outputData[i]*2;

    }
```
But the output is getting heavily distorted.
I also tried 0.2f instead of 2, but still its getting distorted.

**Comment by dturner** [comment]
In the LiveEffect sample both the recording and playback streams are `AudioFormat::I16` i.e. 16 bit integers. Casting to `float` is going to cause the distortion you hear so instead just cast to `int16_t` and multiply by a constant amplitude. 

Make sure to check that the scaled up sample value isn't above `INT16_MAX` otherwise you'll get wraparound and distortion.  

Feel free to reopen if you still have questions.

**Comment by dturner** [comment]
Posted a very similar answer on stackoverflow as well: https://stackoverflow.com/questions/55384777/how-to-amplify-audio-data-in-oboe-onaudioready-method/55473068#55473068

**Comment by j4zib** [comment]
> Posted a very similar answer on stackoverflow as well: https://stackoverflow.com/questions/55384777/how-to-amplify-audio-data-in-oboe-onaudioready-method/55473068#55473068

Thank you, It's working. 
I implemented it like this
`auto *outputData = static_cast<int16_t *>(audioData);
    for (int i = 0; i < numFrames*mOutputChannelCount; ++i){
        outputData[i] = (int16_t)(outputData[i]*mMul)>INT16_MAX?INT16_MAX:(int16_t)(outputData[i]*mMul);
    }`

**Comment by dturner** [comment]
You should also check the lower bound `INT16_MIN` as well. Also, it'd be more efficient to calculate the scaled sample value once, then check whether it needs limiting to the INT16 range. 

pseudo code inside for loop: 

   int32_t sampleValue = outputData[i] * multiplier;
   if (sampleValue > INT16_MAX) sampleValue = INT16_MAX;
   if (sampleValue < INT16_MIN) sampleValue = INT16_MIN;
   outputData[i] = static_cast<int16_t>(sampleValue);
