### ISSUE TITLE
Why Oboe only enqueue one buffer?

### ISSUE THREAD

**Issue by fyfcauc** [google/oboe#464]
I read the source code. From AudioStreamOpenSLES.cpp, I find that Oboe only enqueue one buffer. This confuse me, from the tutorials I learn, eg, openSLES spec sample, and google android NDK sample, for stream playing, they suggest that at least 2 buffer should be enqueued(The ijkplayer even enqueue 200+ buffer), then when one buffer is processed over, the other buffer start play, this avoid the choppy. Could you pls explain why Oboe only enqueue one(then enqueue buffer in callback)? or Maybe my understanding has some mistake? Thx~

**Comment by dturner** [comment]
When opening an OpenSL ES stream, the stream is configured for a buffer size which is double the burst size (i.e. 2 buffers).

Relevant code: [Constant](https://github.com/google/oboe/blob/c4f0a41ba1a85741be7898962fd31c2282cb4e62/src/opensles/AudioStreamOpenSLES.h#L31), [Stream configuration](https://github.com/google/oboe/blob/c4f0a41ba1a85741be7898962fd31c2282cb4e62/src/opensles/AudioInputStreamOpenSLES.cpp#L100).

If you're not using a callback (which you should be for a low latency stream) then the stream has an intermediate buffer provided by `AudioStreamBuffered` and you can set the intermediate buffer size by calling [setBufferSizeInFrames](https://github.com/google/oboe/blob/master/src/opensles/AudioStreamBuffered.cpp#L214). If the stream *is* using a callback then `setBufferSizeInFrames` returns `NotImplemented` since OpenSL ES does not allow a buffer size to be changed once it's been opened. 

That said, perhaps the default OpenSL ES buffer size should be user configurable prior to stream opening.

**Comment by dturner** [comment]
As far as we're aware there's no benefit to allowing the OpenSL ES buffer size to be user configurable, hence why this is not offered in the API.

**Comment by fyfcauc** [comment]
@dturner Thx for your explain~, but What I want to know is that: why oboe only enqueue one buffer at starting ? From this tutorial: http://sbcgamesdev.blogspot.com/2013/01/simple-streaming-audio-mixer-for.html

**Comment by dturner** [comment]
Here's what I *think* happens: 

When an OpenSL ES stream is set to PLAYING state it requires a single enqueue operation to kick off the callbacks. If the SLES buffer isn't full (2 bursts in this case) then there's an immediate 2nd callback which will fill the buffer completely.

The SLES buffer will always attempt to run full (otherwise what's the point in specifying the buffer size?) 

@philburk @gkasten Is this correct?

**Comment by dturner** [comment]
Relevant code: https://github.com/google/oboe/blob/master/src/opensles/AudioOutputStreamOpenSLES.cpp#L301

**Comment by dturner** [comment]
Turns out I was mostly wrong about the way OpenSL ES handles buffers. I will post an update as soon as I've confirmed the exact behaviour.

**Comment by dturner** [comment]
Next steps: See BT latency bug, review Glenn doc, increase numBuffers and test latency.

**Comment by philburk** [comment]
Experiment:  In Oboe, I modified kBufferQueueLength.
I then measured the output latency using Tap-to-Tone in OboeTester.

kBufferQueueLength => latency
        1 buffers => 27 msec
        2 buffers => 30 msec
        3 buffers => 32 msec
        4 buffers => 34 msec
        6 buffers => 40 msec
        8 buffers => 43 msec
       10 buffers => 43 msec
       12 buffers => 41 msec

So the latency is increasing as I declare more buffers up to a limit of 8 buffers. Then it plateaus.
Note that I am always just enqueuing one buffer to start the flow.  So I think the second buffer is getting used.

**Comment by dturner** [comment]
OpenSLES numBuffers property is used to set the size of the underlying AudioTrack buffer. So if you set 8 buffers you'll end up with 8*SLES internal buffer size. When the first buffer from Oboe is enqueued it's placed at the start of the buffer and you are likely to then receive 7 subsequent callbacks to fill up that buffer.   

Oboe is doing the right thing in using `kBufferQueueLength` as 2 and enqueuing one buffer to kick off the callbacks. WAI.

**Comment by cerupcat** [comment]
@dturner When using OpenSLES, I'm getting choppy audio when `kBufferQueueLength` is `2` on many devices. When I increase it to 4 (or higher) the choppiness goes away. Since `kBufferQueueLength` isn't configurable (unless modifying the codebase), is there a different setting that should be used that would give the same result? I'm using an output callback (and reading from the input in that callback) using similar code to the FullDuplexStream example.
