### ISSUE TITLE
Very low output (or input) sound in LiveEffect

### ISSUE THREAD

**Issue by ahmafi** [google/oboe#475]
I can't hear anything until turn my volume to it's maximum. Is it normal?

**Comment by philburk** [comment]
What phone?

Which Android?

Are you using a headset? Does it have a microphone on it?

Which volume fader? Media?

**Comment by ahmafi** [comment]
Samsung Galaxy Note 5
Android 7.0.0
I have tested with a headphone and a headset with the same results. Both have microphones.
I am not sure about your last question! I just installed the sample program without any changes.

**Comment by ahmafi** [comment]
I have also got the same results with Samsung Galaxy J7 (Android 8.1.0) and another set of headphones.

**Comment by dturner** [comment]
The LiveEffect sample just captures the input from the microphone and plays it through the speakers/headphones. You'll only hear something if you actually make a noise. It works best with headphones, otherwise you'll get a positive feedback loop between the speaker and microphone which won't sound nice at all. 

Please re-open if you still have issues.
