### ISSUE TITLE
Documentation request for how to read data from two microphones at the same time.

### ISSUE THREAD

**Issue by Artaches** [google/oboe#483]
Hello, thank you for building Oboe! I'd like to read data from both at the same time, and I was unable to find any documentation on how to do this. I couldn't find this being done in any of the sample either. Please refer to this StackOverflow post for the description of my failed attempts to get this working: https://stackoverflow.com/questions/55979907/how-to-read-data-from-multiple-microphones-using-androids-oboe-aaudio

Any help will be greatly appreciated!

**Comment by PindongaFlores** [comment]
@Artaches : that is NOT possible, it is apparently a limitation of Android. Your question is related to this:
https://github.com/google/oboe/issues/311
That's why I requested a new feature, check this issue:
https://github.com/google/oboe/issues/393
I pointed to the following link:
https://issuetracker.google.com/hotlists/1470752/edit#basic
but I think my request landed in nirvana...maybe you have more luck than me and can make a "proper" Feature Request to Android. Good luck!

**Comment by PindongaFlores** [comment]
why do people don't get a "fast and direct answer" to their questions when it is about the IMPORTANT LIMITATION of Android and Oboe that ONLY ONE Device is supported at a time?...probably because this is a very important limitation related to the fact that latency is still too high?..but what about those users who don't care about some additional delay?..for those poeple more than one device should be available...I requested this feature but no reaction up to now!

**Comment by philburk** [comment]
You cannot directly address individual microphones.

But I have found that if you open a stream with a channelCount=3 then each channel may correspond to an individual microphone - bottom, top and back.
