### ISSUE TITLE
Need to .gitignore more gradle files

### ISSUE THREAD

**Issue by philburk** [google/oboe#504]
I built hello-oboe and now these files are showing up as untracked.
They should be in .gitignore

	samples/hello-oboe/gradle/
	samples/hello-oboe/gradlew
	samples/hello-oboe/gradlew.bat
	samples/hello-oboe/local.properties

**Comment by atneya-nair** [comment]
Those files should not be generated when building the samples (since they are individual modules built by reference to the gradle scripts in the top level samples directory). I don't see them generated when I build the samples either. If you clean them, they (probably) should not reappear when you build.

**Comment by dturner** [comment]
Phil to try cleaning

**Comment by atneya** [comment]
@philburk did cleaning solve the issue, if so can we close?

**Comment by philburk** [comment]
No problem now. I think the problem was that I was building hello-oboe directly instead of from the top level meta-project.
