### ISSUE TITLE
[samples/MegaDrone] Crashes when onResume is called

### ISSUE THREAD

**Issue by dturner** [google/oboe#521]
MegaDrone sample crashes with the following error when onResume is called.
Test device: Samsung Galaxy S5 API 23 (MMB29M)

Steps to repro

- Run MegaDrone app
- Press power button (causing `onPause`) to be called (screen goes off)
- Press power button again (screen back on) and unlock

Expected result

- App is running as normal and can produce sound

Actual result

- App crashes with the following logcat output:

    05-22 18:46:55.797 19943-19943/com.example.oboe.megadrone A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xcc6d8510 in tid 19943 (.oboe.megadrone)

Probably related to #511

**Comment by philburk** [comment]
@atneya-nair - you may be able to repro this by requesting OpenSL ES on a more recent device.

@dturner - can you provide a bugreport or stack trace to Atneya through internal channels if we cannot repro?

**Comment by atneya-nair** [comment]
I can repro on any device. 
It looks like AudioEngine does not go out of scope since it is a global variable in the JNI bridge class. I replaced it with a pointer and reinit. on resume fixes functionality, but the delete of AudioEngine crashes.

I pushed on the branch issue-521 if you could take a look @dturner . Other than the memory issue which I am unsure of, it fixes functionality.

**Comment by atneya-nair** [comment]
I'm going to go ahead and open a PR so its easier to keep track of things even though its still in progress.
