### ISSUE TITLE
Adjusting Input Volume in LiveEffect

### ISSUE THREAD

**Issue by mwh50** [google/oboe#570]
Hey! I'm working on a project where I need to be able to adjust the input (mic) and output (speaker) volumes independently. I have two seekbars that allow the user to input the desired values. Right now I am successfully able to adjust the output volume without going through oboe using the code line below:
`mAudio.setStreamVolume(stream, progress, AudioManager.FLAG_PLAY_SOUND);`

However, I am currently unable to control the input volume. The way I've been trying to do is trying to pass the seekbar value to the LiveEffectEngine.java file. Is this the way I should be doing it or is there an easier way? If it is the right way, I am stuck on how to accomplish anything with the double that is passed in to the LiveEffectEngine. I have the code below in LiveEffectEngine.java, but I am totally lost on what to do next with how to use micPercentage in oboe:
`static native void micVolume(double micPercentage);`

Any help would be amazing including linking to previous posts though I didn't find any on this specifically. Though I am pretty good with Java, C++ is new to me, but I am trying to learn as best I can!

**Comment by atneya** [comment]
Generally speaking, volume is applied to the output rather than the input. The way in which audio input can be made "louder" is applying a *gain* effect. This would involve multiplying the raw audio values from the input stream by a particular amount. Android internally applies a gain to the audio input, so it is reasonably audible. 

A word of caution -- applying gain is risky since it could theoretically lead to *clipping* when the input audio exceeds its maximum value. It also amplifies the noise contained in the input. 

Considering this, I would evaluate whether you really need to apply gain to the input side. It would make sense in scenarios where the audio input is not simply being outputted after some processing (file writing comes to mind). However, in a LiveEffect application, only volume control on the output side is necessary, since the input data is only processed then outputted. If it is necessary, before writing to a file for example, you would multiply the raw input audio data provided by Oboe by a fixed amount (maybe double) as well as your micPercentage multiplier.

**Comment by mwh50** [comment]
Thank you so much for the response! I understand that the gain can get dicey when it is greater than 1, but the goal of this is for the micPercentage multiplier to never be greater than 1. 

Your suggestion about multiplying the raw input audio date provided by Oboe by a fixed amount is exactly what I want to do though! I have been trying to find where the raw input data is in the LiveEffect C++ files, but I am struggling to find it. Would you be able to instruct me on where that raw input data is called or what would be the best way to put that multiplication step in?

Thanks again, I really appreciate the help.

**Comment by atneya** [comment]
If you are using the LiveEffect sample as a starting point:

https://github.com/google/oboe/blob/master/samples/LiveEffect/src/main/cpp/FullDuplexPass.h

This class overrides onBothStreamsReady(), which is called whenever Oboe has input to process and subsequently output. Right now, this class simply passes the input data through unchanged  (this is what `memcpy` does). You would want to multiply the values. 

Since the pointers passed to the method are raw, you would need to cast the void pointer to a int/float pointer (depending on audio format), and treat it as an array with size numInputFrames. You can then multiply over the array. Let me know if you have any other questions.

**Comment by mwh50** [comment]
I'll start by saying thank you for the help you are providing! I tried to do what you have recommended doing, but I seem to be messing up (likely with the pointers). The code I've been editing and adjusting in FullDuplexStream.h without success is shown below:

![image](https://user-images.githubusercontent.com/39747708/61159476-2b668980-a4ca-11e9-8b33-4629b4758fa6.png)


Again any advice or help is super helpful. Thanks!!!

**Comment by atneya** [comment]
inputData is const (should not be mutated). You get around this by casting. 

Instead of using memcpy, cast outputData, and in your for loop: `for (int i = 0; i < numInputFrames; i++) ofp[i] = 0.5  * ifp[i];` 

Then to zero out: `for(int i = numInputFrames; i < numOutputFrames; i++) ofp[i] = 0`

You won't lose performance by using simple loops instead of `memset` or `memcpy`, the compiler should optimize away for you.

**Comment by mwh50** [comment]
I tried following what you said in the code below to no avail.
![image](https://user-images.githubusercontent.com/39747708/61224540-c2129080-a6ec-11e9-8dcf-5835f9fd1d6a.png)
I tried various variations including this, but it did not work either.
![image](https://user-images.githubusercontent.com/39747708/61224486-b030ed80-a6ec-11e9-8c40-b7904f7e8042.png)


I'm very sorry if I am misinterpreting what you are saying. Thanks again for the help! I definitely would not get this without you!

**Comment by mwh50** [comment]
To be more clear, the first screenshot of code works in the sense that if you set the constant that ifp is multiplied by to 0, it mutes the stream. However, when I multiply ifp by 0.5, the program just produces static.

**Comment by philburk** [comment]
> inputData is const (should not be mutated). You get around this by casting.

I would not recommend that. The inputData pointer passed from AAudio might be memory that is owned by the service and may be READ_ONLY. It might work today but might not work in the future. If memory is declared const then do not modify it. Copy the data to another buffer before modifying it.

> if you set the constant that ifp is multiplied by to 0, it mutes the stream.
> However, when I multiply ifp by 0.5, the program just produces static.

That sounds like a format issue. An int16 or a float with all bits set to 0 will be zero. But scaling by 0.5 requires that the format is correct.

@mwh50  Are you sure that both streams are Float format? You can use:

if (stream->getFormat() == AudioFormat::Float)

to check.

**Comment by atneya** [comment]
Closing question due to inactivity.
