### ISSUE TITLE
A few questions regarding Oboe vs OpenSL ES

### ISSUE THREAD

**Issue by stevenhaggerty** [google/oboe#619]
Hi there,

I'm about to re-write our legacy OpenSL ES Android game audio routines as they are error prone and a bit out of date. I need to know if Oboe is a suitable replacement. It'll be used for Android games featuring streaming audio, but mostly just spot effects and some 3D audio.

Please tell me if my assertions are correct:

1)The documentation is fairly thin, and I'm either missing something or the API is simply a very thin layer that allows you to poke waveform data into a stream via callbacks. It then routes them to SLES or AAudio depending on API level.

2)There is no mixer as part of the API, despite being included in the "FullGuide" diagram. 

3)Anything other than single channel audio (1 track in your parlance) will require the user to create their own mixer.

4)There are no facilities for volume/pan/pitch. These will the user to implement them in a renderer.

5)There is no support for playing low sample rate (say 11k, 8 bit mono) on the default Stream, as it'll probably be 48k 16bit. So all audio will either have to be re-authored, or re-rendered into a format matching the native format of the created Stream at post-load time.

6) SharingMode::Exclusive - " If the exclusive endpoint is already in use, it might not be possible for the stream to obtain access to it." Surely this renders exclusive mode unusable? I can't ship an app that may not be able to play audio. Maybe I misunderstand the feature.

7) The android lifecycle is not mentioned. At the moment, with SL ES, we need to set the channels into a "paused" state onPause() and unpause them onResume(). Is something similar required here?

That seems like quite a lot of work, some of which SL ES already does (pitch/pan/etc).

Many thanks for your help,

Steve.

**Comment by philburk** [comment]
Hi Steve,

Good questions.

> I'm about to re-write our legacy OpenSL ES Android game audio routines as they are error
> prone and a bit out of date. I need to know if Oboe is a suitable replacement.

Yes. Oboe will just call OpenSL ES on old platforms. But an advantage for Oboe is that it is supported by Google and there is a large community of developers using Oboe. So if there is a bug in Oboe it will probably get fixed pretty quick. Or you can fix it and contribute the fix back to the community.

1500 heads are better than one.

> 1)The documentation is fairly thin, and I'm either missing something or the API is
> simply a very thin layer that allows you to poke waveform data into a stream via 
> callbacks. It then routes them to SLES or AAudio depending on API level.

That is a good description. In AAudio and Oboe we concentrate on providing a minimal audio I/O API on multiple platforms and versions. Developers can then do their own mixing, format conversion , etc. Developers don't need an OS to do that.

> 2)There is no mixer as part of the API, despite being included in the "FullGuide" diagram.

The mixer is for mixing audio between apps with system sounds. It is inside the Android framework.

We strongly recommend that apps do their own mixing. The overhead for multiple Oboe stream is much higher than for multiple application streams. And you can get lower latency and avoid some bugs in OpenSL ES.

> 4)There are no facilities for volume/pan/pitch. These will the user to implement them in a renderer.

Yep. That is all just math. You don't need an OS for that. Someone can build a multi-sound engine on top of Oboe.

> There is no support for playing low sample rate (say 11k, 8 bit mono)

We just now added support for resampling in Oboe. This is hypocritical of me because resampling is just math. But the math was hard. For a single stream:

```
   builder->setSampleRate(44100);
   builder->setSampleRateConversionQuality(SampleRateConversionQuality::Medium);
```

If you need to do your own resampling, you can find the source code in oboe/src/flowgraph/resampler/MultiChannelResampler.h

> SharingMode::Exclusive - " If the exclusive endpoint is already in use, it might not be
> possible for the stream to obtain access to it." Surely this renders exclusive
> mode unusable? I can't ship an app that may not be able to play audio. 

There is only one MMAP EXCLUSIVE data path. If you cannot get it then you will go through AudioFlinger FAST track. The latency will still be low but not as low. You will still get audio out.

> The android lifecycle is not mentioned.

The same concepts apply. But it is especially important to close an EXCLUSIVE stream when not using it.

**Comment by stevenhaggerty** [comment]
Ah, that's really helpful, many thanks.

I'm afraid a phrased my question about sample rate, poorly. I was referring to input audio files rather than the stream itself.

For example my app may have audio files of different sample rates. 11k mono, 16k mono and 22k stereo (for example). This may have been done to keep apk size down.

If after creating the stream, I find the native stream rate is 48k stereo, I'd like to resample those input files after load to match the native stream and stick to the fast path.

As you mentioned, I'd have to write a resampler. The MultiChannelResampler class you mentioned looks ideal. Rather than cut & paste this code, would it be possible to expose the MultiChannelResampler class that is part of the Oboe source, rather than developers cutting and pasting something that's already present (but not exposed)? 

This would also keep us up to date with improvements / fixes.

Thanks again,

Steve.

**Comment by philburk** [comment]
> Rather than cut & paste this code, would it be possible to expose the
> MultiChannelResampler class that is part of the Oboe source

The resampler is still experimental. We have not yet determined what the final API should look like. It might change slightly in the future. For now, you could just include the internal header "src/flowgraph/resampler/MultiChannelResampler.h". But do so at your own risk because it might change soon.

When the API settles down we may export the API for flowgraph and resampler.

BTW, use the lowest quality that sounds good to you. That will save CPU time. The higher qualities can be expensive.

We are getting past the original question so I am closing this. Feel free to open a new Issue with a new question. We want the Issue titles to match the contents.
