### ISSUE TITLE
Multipe REAME.md files in repo

### ISSUE THREAD

**Issue by kshithijiyer** [google/oboe#641]

**Comment by dturner** [comment]
This is because there are multiple projects (core library, samples, test apps etc) and each one will have a README.md. Please could you explain why this is a bug.

**Comment by dturner** [comment]
Ah. I understand what you're getting at (although your bug title doesn't explain it). 

There is both a `README` file and a `README.md` file. This is due to our open sourcing policy - every project must have a `README` file. We deliberately point this to `README.md` because then github correctly displays the markdown. 

The same applies to `CONTRIBUTING`.

**Comment by yrezgui** [comment]
Is this issue still open?
