### ISSUE TITLE
LatencyTuner failing and glitches

### ISSUE THREAD

**Issue by extreamsd** [google/oboe#662]
Android Version(s): 10
Android Device(s): Pixel 2
Oboe Version: 1.2.1

**Short Description**
Trying to reduce CPU load, but LatencyTuner's tune() does not change the frames that are requested in onAudioReady() and using setFramesPerCallback() to anything else than the native frames per burst causes glitches.

**Steps To Reproduce**
Problem A:
Call m_latencyTuner->tune(); inside onAudioReady
Problem B:
setFramesPerCallback(96 * 12)

**Expected behavior**
numFrames in onAudioReady() increases depending on the result of tune(). And audio would (eventually) play without glitches.

**Actual behavior**
Problem A:
numFrames stays the same
Problem B:
Audio glitches

**Additional context**
When doing effects processing on audio streams, the native buffer size of 96 frames (at 48000Hz) causes high CPU load (too high actually). The tune() should come to rescue. Debugging tune() shows that it calls setBufferSizeInFrames() successfully up to the max (3072 frames). However, nothing happens in onAudioReady(). It keeps calling with 96 frames. This is without setFramesPerCallback().
Alternatively, I tried using setFramesPerCallback with 1152 frames. Should be plenty for not getting xruns. However, there are glitches and many xruns.

In both situations, Oboe shows that the low latency mode is active.

**Comment by dturner** [comment]
> However, nothing happens in onAudioReady(). It keeps calling with 96 frames. 

You're getting confused between *buffer size* and *frames per callback*. 

By calling `setBufferSizeInFrames` either directly or indirectly using `LatencyTuner::tune` you are setting the buffer size of the stream. This doesn't affect the frames per callback, it just means that more data will attempt to be buffered. In practice this means that `onAudioReady` will be called until the buffer is full, however, if your audio effect is already using loads of CPU this might make no difference because the buffer cannot fill to its new size.  

You might want to try setting the buffer size high and feeding the stream with silence before starting your audio processing. 

It could be that your effects processing is consistently using too much CPU which means no matter how large the buffer you're always going to get underruns sooner or later. This could be confirmed by [running a systrace](https://medium.com/@donturner/debugging-audio-glitches-on-android-ed10782f9c64). 

Post the systrace and we can investigate further.

**Comment by extreamsd** [comment]
Fair enough. But using AudioTrack gives a CPU usage of about 30% without glitches. This is obviously using a larger buffer size of 1924 frames. Question then becomes how to set up Oboe/AAudio to get the same behavior without glitches or slow downs? Something I can reliably do such that all users get a good experience, possibly with need of a buffer size setting that the user can adjust? Now it's too high cpu usage when using the native buffer size and increasing the buffer size doesn't help. 

If I use Oboe/AAudio and use setBufferSizeInFrames(1924) and builder.setFramesPerCallback(1924) which is the buffer size for AudioTrack, I get massive Xruns and audio is slowed down.

**Comment by philburk** [comment]
If bufferSize and framesPerCallback are both set to 1924 then you have no margin for error. You are effectively "single buffered" and I expect it to glitch.

Increasing latency will not reduce glitches if the CPU load is more than the CPU can handle.

If 1924 works for you then try not requesting a low latency stream. You may not need it. Try:

builder->setPerformanceMode(PerformanceMode::None);

Note that calling setBufferSizeInFrames() does not change the number of frames passed to the callback function. The frames passed will generally be smaller than bufferSizeInFrames because you want to leave some data in the buffer for safety to reduce glitches.

**Comment by extreamsd** [comment]
Ok, I guess I got confused because basically setting the buffer size for all other audio systems means the buffer size of one buffer of a (usually) double-buffered audio system.

LatencyTuner::reset() also does:
mStream.setBufferSizeInFrames(mStream.getFramesPerBurst());
which would be equally hazardous, although one may perhaps not notice because after the first calls to tune(), it would increase it, but perhaps the starting point should be * 2.

**Comment by dturner** [comment]
> but perhaps the starting point should be * 2.

Yes, that's a great idea. 

Did you find the glitching problem?

**Comment by dturner** [comment]
Related #666

**Comment by extreamsd** [comment]
> > but perhaps the starting point should be * 2.
> 
> Yes, that's a great idea.
> 
> Did you find the glitching problem?

Yes, it's like Phil said: the buffer size and frames per callback were equal. Now that I have solved that, the glitches are gone.

**Comment by dturner** [comment]
That's great news. Keep up the good work :)
