### ISSUE TITLE
OboeTester fails on Moto X4 with "Service media.aaudio didn't start"

### ISSUE THREAD

**Issue by dturner** [google/oboe#702]
Android Version(s):
Android | PPWS29.69-37-5

Android Device(s):
Motorola Moto X4 

Oboe Version:
1.2.4

OboeTester Round Trip latency test fails with logcat error message: 

Error: Service media.aaudio didn't start. Returning NULL

**Steps To Reproduce**
1. Run OboeTester
2. Tap Round Trip Latency
3. Tap Measure

**Expected behavior**
Round trip latency test runs successfully

**Actual behavior**
App hangs and the following error message can be seen in the logcat output: 

W/ServiceManager: Service media.aaudio didn't start. Returning NULL

**Comment by philburk** [comment]
Does LiveEffect sample behave the same way?
Does an older version of OboeTester work on the Moto X4?

**Comment by philburk** [comment]
Is this reproducible? x/10?

What happens if you enter: 
    adb shell dumpsys media.aaudio
    adb shell getprop | grep aaudio

Can you please attach more logs, starting with the Open call to Oboe?

**Comment by dturner** [comment]
Next steps: Obtain an X4 and X10 and run tests as per Phil's instructions

**Comment by philburk** [comment]
I think I know what was happening. A bug in OboeTester caused MMAP to be enabled even though MMAP was not supported on that device. So AAudio would try to open the service for MMAP but it didn't exist. So it would hang for 30 seconds then timeout. That can seem like forever.

I saw this on a Xiaomi phone, which also does not support MMAP.

I am pretty sure this was fixed by: https://github.com/google/oboe/pull/723

@dturner You can verify with the current OboeTester or just close it.

**Comment by suicide333** [comment]
> Android Version(s):
> Android | PPWS29.69-37-5
> 
> Android Device(s):
> Motorola Moto X4 
> 
> Oboe Version:
> 1.2.4
> 
> OboeTester Round Trip latency test fails with logcat error message: 
> 
> Error: Service media.aaudio didn't start. Returning NULL
> 
> **Steps To Reproduce**
> 1. Run OboeTester
> 2. Tap Round Trip Latency
> 3. Tap Measure
> 
> **Expected behavior**
> Round trip latency test runs successfully
> 
> **Actual behavior**
> App hangs and the following error message can be seen in the logcat output: 
> 
> W/ServiceManager: Service media.aaudio didn't start. Returning NULL
>
