### ISSUE TITLE
getSampleRate() returning 0 when...

### ISSUE THREAD

**Issue by cyb3rc0lby** [google/oboe#704]
when it's not explicitly set with setSampleRate(int);
even though im using
 oboe::DefaultStreamValues::SampleRate = (int32_t) defaultSampleRate;
to set a default sample rate upon my app's initialization. is that normal behavior?

edit: this is also true for getFramesPerCallback(), which i dont even set, but still, shouldnt these values be filled out after i open the stream with the builder?

**Comment by philburk** [comment]
Are you calling getSampleRate() on the builder or on a stream? The stream should have a nonzero sample rate after it's opened. Also what version of Android are you using?

**Comment by cyb3rc0lby** [comment]
@philburk on the builder. Android OS 7.1.1.   It still seems to work, but that function is reporting 0

**Comment by philburk** [comment]
If the builder returns 0 that just means that you have not specified it on
the builder. That is legal. Once you open the stream you'll get an actual
sample rate and you can query that. It will be non-zero.

**Comment by cyb3rc0lby** [comment]
that's not what's happening. after i open the stream with this:
    oboe::Result result = builder.openManagedStream(managedStream);
i go to print the sample rate with this: 
    LOGI("OSC SAMPLE RATE: %d",(int)builder.getSampleRate());
and if the sample rate is not explicitly set, it prints 0. otherwise it will print what it is set to.

**Comment by atneya** [comment]
To clarify, there is a difference between the sample rate set in the builder, and the sample rate set in the actual ManagedStream.

For example, when you call
`builder.getSampleRate()` 
this returns the sample rate of the **builder**, which is zero since it was never set.

On the other hand, if you were to call 
`managedStream->getSampleRate()` 
it would return the sample rate of the MangedStream object `managedStream`, which is presumable how you are outputting audio, and what is of direct interest.

To answer your question above, the `DefaultStreamValues` in Oboe set the default values of the **ManagedStream** objects, not the AudioStreamBuilder objects, which is why the value of the builder is zero if it is not explicitly set.

**Comment by philburk** [comment]
The code is working as intended.
