### ISSUE TITLE
Passing data from Java to Oboe

### ISSUE THREAD

**Issue by abu100** [google/oboe#705]
Hey,
I am developing an android application that multicasts audio to other smartphones. I want the audio to play on all devices simultaneously, however, each phone has different playout latency using Java AudioTrack API. I want to use Oboe to get the fastest path but the FAQ section says passing data from Java to Oboe is not a good option. It says to use the Low Latency performance mode which is better than Oboe. Can you please guide me as to what to do in this scenario?

**Comment by philburk** [comment]
If latency is not an issue then I recommend using the Java audio track API because it has timestamps. You can use the time stamps even on much older versions of Android to synchronize the output of the various devices. You could start all the streams playing silence until you get valid timestamps. Then start the valid audio data with the correct offset on each device so that all the frames line up at the same time.

**Comment by abu100** [comment]
Hey Philburk, 
Thank you so much for the reply and  valuable suggestions. I read up on AudioTimestamps and found them useful for audio/video sync. However I plan on syncing multiple android smartphone audios. Can you please elaborate how to use timestamps for that? 

Secondly, one of the reasons for using Oboe was to calculate audio output latency. Since I cant use that in my scenario, what other ways can I use to get Android Output Latency other than the Pro and Low_latency Flags?

**Comment by philburk** [comment]
> Can you please elaborate how to use timestamps for that?

Sorry. You'll need to figure that out. Basically you start the streams, look at the timestamps and then align the audio in your output streams so that the presentation times match on each device.

>  what other ways can I use to get Android Output Latency other than the Pro and Low_latency Flags?

I don't understand the question. You can measure latency using timestamps, assuming the timestamps are correct.
