### ISSUE TITLE
New Android 10 on Samsung Galaxy causes aaudio issues

### ISSUE THREAD

**Issue by peterdk** [google/oboe#726]
Android Version(s): 10
Android Device(s): Galaxy S10
Oboe Version:

**Short Description**
I got report from user that just upgraded to the new Android 10 on his Samsung Galaxy S10 that audio now cracks, has delays and crashes app and sometimes whole device. I am not using oboe, but am using AAudio (with underrun logic) and thought you guys should know that Samsung's release has issues. I'll try to get my hands on a Samsung with the new release to test it myself, but it's a bit worrysome. On Nokia's Android 10 I have no issues.

**Comment by philburk** [comment]
We are obviously very interested in any detailed information you have about
this. Do you know if it was an Exynos device or Qualcomm device? Was this
the first Android 10 release or an update?

Any error messages or crashed stocks or any clues to what might be
happening?

Does it happen on open or close or when plugging or unplugging headsets?

Are you using low-latency mode?

**Comment by philburk** [comment]
Also, what is the exact build number? That is important for regressions.

If you run OboeTester then it will show up at the bottom of the first screen.

**Comment by peterdk** [comment]
I unfortunately don't have any crash reports. I tried to get in touch with the (Korean) user, but haven't heard back. If I do then I will update. 
I

**Comment by philburk** [comment]
@peterdk - what kind of app is this? Game? Music? VoIP?

Output only? Record only? Both?

Is it on the Play Store so we can test it here?

> am using AAudio (with underrun logic)

What is the lowest level that you set the bufferSize to? If it is too low then there may be glitching that does not show up as XRuns. But that should not cause a crash.

**Comment by peterdk** [comment]
I did not hear back from the user, and can't find a crash on Android 19 anywhere in play console and Crashlytics. So I am thinking this is a false report or not related to the app.

I can't test with a S10, since I don't have one.
It's a piano app. Output only.  Buffersize start is the framesperburst returned by AAudio and also used as increment per underrun.
App can be found here:
https://play.google.com/store/apps/details?id=umito.android.minipiano

**Comment by philburk** [comment]
I tried the Umito Mini Piano on an Exynos S10 running P. Nice app!
It ran fine. I will try to run it on Q.

The latency is a little higher than I would expect. It may be due to speaker latency. I will investigate that. What input event are you using to trigger the sound?

>  I am not using oboe, but am using AAudio (with underrun logic) 

You might consider using Oboe. It will let you run the same code on old devices with OpenSL ES. And it has workarounds for known issues on certain devices and certain versions. If we find a problem on the S10 we might add a workaround to Oboe, but not to AAudio, because Oboe is statically linked.

Porting from AAudio to Oboe is pretty easy.

May we add your apps to the list of known AAudio/Oboe apps? Then they will get some extra testing.
https://github.com/google/oboe/blob/master/docs/AppsUsingOboe.md

**Comment by peterdk** [comment]
Ok, great! Thanks. 
I think the increased latency is due to my resampler I am using. I just discussed the issue with them (r8brain-free) and got it working faster but that will be released in January.
I do have OpenSLES implemented for 8.0-. 
I will try Oboe to see if it is faster. Does it handle resampling?

**Comment by philburk** [comment]
> I will try Oboe to see if it is faster. Does it handle resampling?

The new Oboe 1.3 has a sinc based resampler. You have to enable it because it is new.
https://google.github.io/oboe/reference/classoboe_1_1_audio_stream_builder.html#af7d24a9ec975d430732151e5ee0d1027

builder.setSampleRateConversionQuality(SampleRateConversionQuality::Medium);

> I use the ontouch event to call the native layer 

Probably similar to this:
https://github.com/google/oboe/blob/master/apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/FastButton.java

> Touch to render time is 5ms.

That is very small latency.
You might want to try the Tap-To-Tone latency test in OboeTester for comparison.
https://github.com/google/oboe/blob/master/apps/OboeTester/docs/Usage.md

I added your app:
https://github.com/google/oboe/blob/master/docs/AppsUsingOboe.md
