### ISSUE TITLE
Random lost sound.

### ISSUE THREAD

**Issue by nocola** [google/oboe#767]
Android Version(s): Android 6 | 7 | 8.0 | 9
Android Device(s): Samsung Galaxy S7, Samsung A50, M4, Lenovo K10A40, Honor, Oppo.
Oboe Version: checked for 1.2, 1.1.0, 1.1.1, 1.3

Using callback for outStream I read from inputStream with some audio processing. 
And it works. BUT from time to time, the callbacks stop coming on the start, for some devices less often for others more often. It looks like streams was opened, send several callback and then stop sending. 
No crashes (I throw runtime_error if streams was not open).

The pain is that in most cases it works and is detected only by accident.

**Comment by philburk** [comment]
Thanks for reporting this. It sounds like something fairly deep inside the framework.
We would need a bugreport file to figure this out.
Can you please file a bug starting with this link:

    https://source.android.com/setup/contribute/report-bugs

Please do not attach bugreports to GitHub issues because the bugreport may contain private information. That is removed when files on the Android site.
