### ISSUE TITLE
DrumThumper sound is corrupted when the app goes into pause state

### ISSUE THREAD

**Issue by LordByron1788** [google/oboe#784]
This issue follows on from #768 

If I substitute a mono piano wave file for one of the drum samples. The sound initially works fine. However, when the app goes into pause state a few times, the sound becomes corrupted (i.e very distorted). The issue is something to do with this line:
mAudioMgr!!.unregisterAudioDeviceCallback(mDeviceListener)

Please go to #768 to get the piano wav file,

**Comment by ekurdesov** [comment]
Could you please help me to get going with the project? It's not building for me at all. my email is ekurdesov@gmail.com :) sorry for offtopic but I'm looking to find a solution everywhere. sounds like it's building for you

**Comment by LordByron1788** [comment]
> Could you please help me to get going with the project? It's not building for me at all. my email is ekurdesov@gmail.com :) sorry for offtopic but I'm looking to find a solution everywhere. sounds like it's building for you

What issue are you facing? It would be better to create a separate issue, and write whatever error messages you are encountering there.

**Comment by philburk** [comment]
Maybe related to Android Activity onPause() onResume().

**Comment by android-usb** [comment]
Yes. Handling Activity onPause() onResume()  along with mUseDeviceChangeFallback to restart the stream.

Current code addresses this problem.

**Comment by LordByron1788** [comment]
I downloaded the latest version for Drumthumper, and tried the same process. I substituted one of the files with the "piano_mono.wav" file. After sending the app into the backgroud, and resuming it, the sound is completely distorted.  Are you planning on to do another release that has fixed this? is that why this has been closed? If not, then please can you test on an actual physical device, since this issue still exists. Also, please consider reopening this github issue. Thank you.

**Comment by android-usb** [comment]
2 things:
Does the "corruption" happen with the default (drum) samples?
Try setting the value of mUseDeviceChangeFallback (in DrumThumperActivity.kt) to false.

What device are you running on?

**Comment by LordByron1788** [comment]
The device is a Samsung Galaxy A10, and yes, the default (drum) samples are also effected but to varying degrees.

Mid/Low Tom - both significantly affected (as bad as piano_mono)
Snare/Crash/closed hat - moderately affected
Open/Ride  - slight affected

To replicate the issue, I just have to put the app into the background twice, before the sounds get corrupted. By "corruption", I mean the sound is either distorted and/or shortened noticeable to a user.

**Comment by dturner** [comment]
I also ran into this issue. Seems that backgrounding the app multiple times results in distortion when playing. I was testing on a Pixel 3.

**Comment by ekurdesov** [comment]
I was able to resolve those issues by moving the library creation and Players to the service layer. Now I can even play with the screen off :) Don't ask me why just google #stompai :)
With the screen off  - the happiness doesn't last long though. Android kills my service in a minute or so) If you guys know how to resolve this I'd be super happy.

The current build of the DrumThumper works well on Google PIxel1 but I'm able to corrupt the sounds by clicking the volume dialog, even though it seems like onPause and stopped functions are called it doesn't fix the corrupted sounds. When I swap the apps it works as expected. 

With my approach, there is another issue that I explained here https://github.com/google/oboe/issues/809

There I'm tearing down audioStream to create a new one and since its calling from the service it's crashing the app. as a workaround, I'll try to create just a new audioStream and a new player for new sound groups, will have that tested this weekend. 

I had 1 issue with the sounds. Sometimes if you feed to the player files it's reading them as 48000 and it usually leads to the app crashes. To replicate add some file to your folder of sounds with 48000 while other files are 44100

**Comment by philburk** [comment]
I can replicate this bug:

1. Launch DrumThumper
2. Tap "Mid Tom" ten times. They sound fine.
3. Click Android HOME button.
4. Relaunch DrumThumper
2. Tap "Mid Tom" ten times. 

EXPECT:  good sound.

ACTUAL: the fifth and subsequent taps play with a very distorted sound

**Comment by android-usb** [comment]
I can replicate also on a Pixel 3XL when the "device change fallback" mechanism IS NOT being used.
i.e. in DrumThumperActivity.kt,  mUseDeviceChangeFallback = false;

if I set mUseDeviceChangeFallback to true, I do not encounter this problem.

Phil, can you try that please?

**Comment by android-usb** [comment]
Fixed a while ago.
