### ISSUE TITLE
Why an example doesn't work for me

### ISSUE THREAD

**Issue by bratyslav** [google/oboe#797]
Android Version(s): 5.0.2
Android Device(s): ?
Oboe Version: latest version 02/01/2020

Hello, I'm trying to use an example from your video (https://www.youtube.com/watch?v=cyMD4TJxIPA) to analyze the input audio signal. I literally rewrote this code from the video example, but the result.value(), returned by stream->read() contain 0 (meaning read zero frames), and I can't understand what I'm doing wrong. I will be very grateful if you can tell what could be the problem.
(Also there are no errors by opening and starting stream).

```c
#include <jni.h>
#include <string>
#include <oboe/Oboe.h>
#include "oboe/apps/OboeTester/app/src/main/cpp/android_debug.h"
std::string VOID = "VOID";

using namespace oboe;

extern "C" JNIEXPORT jstring JNICALL
Java_my_motionsensor_MainActivity_audioSignal(JNIEnv* env, jobject /* this */)
{
    AudioStreamBuilder builder;
    builder.setDirection(Direction::Input);
    builder.setPerformanceMode(PerformanceMode::LowLatency);

    AudioStream *stream;
    Result r = builder.openStream(&stream);
    if (r != Result::OK) LOGE("Error opening stream %s", convertToText(r)); // No errors

    r = stream->requestStart();
    if (r != Result::OK) LOGE("Error starting stream %s", convertToText(r)); // No errors

    constexpr int kMillisecondsToRecord = 2;
    const int32_t requestedFrames = (int32_t)(kMillisecondsToRecord * (stream->getSampleRate() / kMillisPerSecond));
    int16_t myBuffer[requestedFrames];

    constexpr int64_t kTimeoutValue = 3 * kNanosPerMillisecond;

    int framesRead = 0;
    do {
        auto result = stream->read(myBuffer, stream->getBufferSizeInFrames(), 0);
        if (result != Result::OK) break;
        framesRead = result.value();
        LOGD("Read %d frames by cleaning", result.value()); // Read 0 frames by cleaning
    } while (framesRead != 0);
    // Here myBuffer is still full of garbage

    auto result = stream->read(myBuffer, requestedFrames, kTimeoutValue);
    if (result == Result::OK) LOGD("Read %d frames", result.value()); // Read 0 frames

    return env->NewStringUTF(VOID.c_str());
}

**Comment by philburk** [comment]
framesRead will be zero when no frames were read. That can happen because it can take a few hundred milliseconds for the stream get started. It is not an error. It just means the data is ready yet.

In your program, you are only reading one stream. So you may want to use a timeout>0. I would use something like 100*kNanosPerMillisecond.

Also I see a problem. You allocate an array containing requestedFrames int16 samples.

    int16_t myBuffer[requestedFrames];

But if the stream is stereo then you need 2*requestedFrames or you will overflow the buffer and crash.  Also the stream might be AudioFormat::Float. You should either handle whatever format the stream is. Or request a specific format.

    builder.setFormat(AudioFormat::I16);

Also when you read the data you request too much data.

    auto result = stream->read(myBuffer, stream->getBufferSizeInFrames(), 0);

The BufferSizeInFrames is the size of the OboeBuffer. That is much bigger than the buffer you allocated. Do not read more than the size you allocated.

**Comment by reuniware** [comment]
Thank you philburk, that helped me a little (I had some crashes that I resolved thanks to your clues).
