### ISSUE TITLE
DrumThumper sounds are truncated

### ISSUE THREAD

**Issue by kevin-zheng12** [google/oboe#807]
Android Version(s):8.1.0
Android Device(s):DUB-AL00
Oboe Version:The latest version

**Short Description**

I used the drumthumper demo, and when I quickly clicked on one of the instruments, the previous sound felt interrupted. What can I do? Thank you

**Steps To Reproduce**

**Expected behavior**

**Actual behavior**

**Additional context**

If applicable, please attach a recording of the sound.

**Comment by philburk** [comment]
I could not reproduce this.
I ran the current version of DrumThumper.
I clicked the Ride and listened to it slowly decay.
Then I clicked the Ride and a few other drums.
They sounded quickly and when they stopped I could hear the Ride still decaying slowly as before.

@kevin-zheng12  How exactly can we reproduce this?

Which sound interrupts which other sound?

**Comment by kevin-zheng12** [comment]
Thank you very much for your reply. I just clicked on the Crash instrument quickly, but did not click on other instruments. It sounds like the first time the sound is covered by the second time. Is it because the same audio file is always playing?

**Comment by philburk** [comment]
That is a design choice. Each Drum has only one player. That is a reasonable thing to do because if you hit a cymbal a second time then you actually interrupt the first sound.

If you want to make each cymbal sound run to completion then you could allocate multiple players and then assign each drum sound to the "least-recently-used" player. This is also called "voice allocation".
