### ISSUE TITLE
Android Audio Architecture question

### ISSUE THREAD

**Issue by Tim-Kindberg** [google/oboe#844]
Android version(s): 8,10
Android device(s): Motorola G5+, Nexus 5X, Galaxy S10
Oboe version: -
App name used for testing (please try to reproduce the issue using the Oboe samples and apps): Facebook in live streaming mode

Apologies for asking a non-Oboe-specific question here but someone on this forum might be able to answer - and it relates to my failed attempts to use Oboe and AAudio with an external USB audio device around July last year, which I reported in this forum. 

I've been experimenting with Facebook live streaming on Android phones with this external device attached.

There are regular (every few seconds) audio glitches/crackles on some phones. Results vary by model and Android version. E.g. Samsung S9 (Android 10) is fine as is a Nexus 5 (Android 6); Samsung S10 (Android 10) and Moto G5+ produce glitches.

I experienced similar glitches on some phones when writing an app for recording from this external device, and had to resort to using a libusb-based driver - embedded in the app - which I've found works fine on all phones.

My question is an architectural one: is it possible for my app to export this driver to other applications - and to do so transparently, so that those applications will use that driver without modification?

I've looked at the Android architecture and audio architecture but I'm having trouble understanding what is possible at run-time on any android device - as opposed to possible in the android build for a particular phone. The closest I've found on stack overflow is [this attempt](https://stackoverflow.com/questions/39746221/what-is-required-to-make-android-use-a-new-audio-hal) for an app to feed audio to other apps, but there is not enough information for me to understand what is going on.

I'd appreciate: (1) examples of achieving what I want, or (2) reasons why it's not architecturally possible.

Many thanks.

**Comment by philburk** [comment]
> My question is an architectural one: is it possible for my app to export this driver to
> other applications - and to do so transparently, so that those applications will use
> that driver without modification?

I don't think so. If I understand correctly, you would want an app (eg. Facebook) to use a different API for recording instead of the one it is currently using. That would require modifying the Facebook code.

Glitches are a very broad issue with a lot of possible causes. Each phone is different. If you would like us to investigate a specific problem then let's focus on one phone. Ideally running a recent OS like 10. Also please include a short recording. You should start a separate Issue for that. Also, if possible, try to reproduce with OboeTester or one of the sample apps. That will make it easier for us to reproduce in house.
