### ISSUE TITLE
Where to Retrieve Audio Data in LiveEffect? 

### ISSUE THREAD

**Issue by griffinperry** [google/oboe#904]
Android version(s): 10
Android device(s): Google Pixel 3a XL
Oboe version: Latest
App name used for testing: LiveEffect
 
**Short description**
I'm wanting to have an effect similar to the LiveEffect, where audio is flowing in both directions. I'm needing to read the bursts of audio data from my input stream and then send to a FFT implementation for further audio processing. However, I'm having trouble following along with the example as to where this would be retrieved considering the LiveEffectEngine, FullDuplexStream, and FullDuplexPass that seemingly all work together. If you could provide guidance as to where this data could be sent that would be wonderful.

Thank you!

**Comment by griffinperry** [comment]
I now have found issue #852 that seems to be what I'm referring to. I'm assuming FullDuplexPass is where I would be able to modify the stream. Is there any more reference to how to send the input data to something like FFT?

**Comment by philburk** [comment]
The problem with the FFT is that it generally requires a large block of data that is larger than the callback size for Oboe.
I recommend writing your FFT effect so that you can pass arbitrarily sized buffers of input+output data.
You will need to gather input data in a buffer until you have enough to do the FFT/IFFT. 
Then store the result in your own result buffer and read from it for output.

    inputData[96] -> gatherBuffer[1024] -> FFT/IFFT[1024] -> resultBuffer[1024] -> outputData[96]
