### ISSUE TITLE
I want to create a new example

### ISSUE THREAD

**Issue by ashfaq1701** [google/oboe#924]
I started working with Oboe. I want to build a new example and contribute into oboe. I am planning to create a recorded stream and a selected file mixer. There will be two activities, one for recorder and mp3 file selector and another for mixer. On the mixer page there will be option to trim audios. There will be a custom built visualizer. Can I start working on it?

1. Can I use MVVM pattern in android?
2. Can I use Kotlin in the view side?
3. Can I use Dagger2 for dependency injection?
4. Can I use RxJava (although I am not sure if I will use it or not)? If you say it might not be appropriate, I will not use it.

I will take this as a huge learning opportunity and a big transformation in my career. I will give very high effort. I will try to keep high standard in the code. Please give me an opportunity.

**Comment by dturner** [comment]
Sounds like a great idea for an app. It probably wouldn't be accepted into the Oboe samples codebase at this time though since we have plans to consolidate much of the sample code into individual libraries to avoid duplication. Feel free to submit a PR though. 

To answer your questions - yes to all of them, except you probably want to use Hilt for DI. 

Good place to start is: https://developer.android.com/jetpack/guide

**Comment by ashfaq1701** [comment]
Thank you so much! :) 

I will definitely use Hilt. Thank you for your valuable suggestion. This is going to be my future course of actions.

I will submit a PR once it is ready. I will hope that you will like it.
