### ISSUE TITLE
Multiple steams from a single source

### ISSUE THREAD

**Issue by ashfaq1701** [google/oboe#928]
In my app I want,

The audio from microphone

1. Should be relayed to the headphone speakers
2. Should be passed to java / kotlin code in a visualizer view
3. Should be saved in the app's storage location as audio file

All at the same time.

I had read that streams can have a single source and sink. Can I create multiple streams from the same source (microphone) and fed it in different places? Should I follow this approach or something else?

A pointer of the proper way to achieve this will be great. I will find out the details.

**Comment by dturner** [comment]
All of this is technically possible. When you open an input stream you have access to the raw PCM data which can then be copied to wherever you like. 

Because you're passing the audio from the microphone to the headphones it sounds like you need to minimise latency. I would advise the following: 

- Open a low latency output stream with a callback, this will be called when the output stream requires audio data. 
- Open a low latency input stream for the microphone. 
- Inside the output stream callback read from the input stream into a processing buffer, copy this buffer immediately into the output stream `audioData` array so that the output stream gets its data as quickly as possible. 
- Start separate threads for the visualizer and file writing processes, both of which hold their own read pointers to the processing buffer and can read at the their own rate.

Out of interest what are planning on using for the visualizer?

**Comment by ashfaq1701** [comment]
Thank you very much. I can't describe how much these advice helped me.

I am trying to build a audio mixer and editor like audacity for android. First in small scale then gradually adding features (expanding it). Final goal is to create a usable solution which is not just a "toy".

For visualizer I wanted to use this in the first place,

https://github.com/GautamChibde/android-audio-visualizer

But for later scope of expandibility I decided to write a custom view (simple at first). If you have any suggestions, please help me.

**Comment by dturner** [comment]
I took a brief look at the visualizer code and it looks pretty cool. It works by passing it an audio session ID. You can either create one in Java land and pass it to Oboe when it creates its recording stream. Or you can use Oboe to create the session ID and pass it back to Java land. More details here: https://github.com/google/oboe/issues/296

**Comment by ashfaq1701** [comment]
Thank you for this much help. I will use that package as visualizer.
