### ISSUE TITLE
Tab S3 cannot recover from disconnect with AAudio

### ISSUE THREAD

**Issue by extreamsd** [google/oboe#958]
Android version(s): 9
Android device(s): Samsung Tab S3 SM-T820
Oboe version: 1.4.2
App name used for testing: Audio Evolution Mobile Studio
 
**Short description**
Tab S3 cannot recover from disconnect with AAudio

**Steps to reproduce**
Plug in headset
Record
Stop
Pull out headset
Record

**Expected behavior**
Should record from tablet's mic

**Actual behavior**
Recording does not start

**Device**
gts3lwifi

logcat:
11433-11433/com.extreamsd.aemobile D/AAudio: AAudioStream_requestStart(0x7e6bc8bb80) called --------------
682-28906/? I/APM_AudioPolicyManager: AudioPolicyManager::startInput(input:1182, session:5761, silenced:0, concurrency:0)
682-28906/? D/APM_AudioPolicyManager: isConcurentRecordAllowed() isAllowed : 0, secVoip_other(0), curSource(6), newSource(6), curFlag(5), isSecMultiRec(0)
682-28906/? W/APM_AudioPolicyManager: startInput(1182) failed: other input 1174 already started
682-28906/? W/AudioPolicyIntefaceImpl: startInput() status(-38) active input 1086, pid 11433
682-28906/? W/AudioPolicyIntefaceImpl: startInput() status(-38) active input 1174, pid 11433
11433-11433/com.extreamsd.aemobile E/AudioRecord: start() status -38
11433-11433/com.extreamsd.aemobile D/AAudio: AAudioStream_requestStart(0x7e6bc8bb80) returned -895 ---------
11433-11433/com.extreamsd.aemobile D/eXtream: recStarted = 0, res = -895
11433-11433/com.extreamsd.aemobile D/AAudio: AAudioStream_requestStop(0x7e6469be80)

"other input 1174 already started" is probably the issue.
By forcing Oboe to use OpenSLES, the problem does not happen, so it is AAudio specific. Unfortunately, with AAudio, I cannot get recording to work anymore no matter how many times I close and recreate the stream. I have to restart the app before it functions again.

**Comment by philburk** [comment]
I suspect that the error callback is not getting called due to a bug in P. OboeTester has a "TEST DISCONNECT" test to detect this problem.

This page describes the issue in some detail. Please reopen this bug if that page does not answer your questions.

https://github.com/google/oboe/blob/master/docs/notes/disconnect.md

**Comment by extreamsd** [comment]
The error callbacks are being called.

**Comment by philburk** [comment]
OK. The start is failing because another input stream is already active. But why?

-895 is AAUDIO_ERROR_INVALID_STATE

The Tab S3 started with  Android 7.0 (Nougat), upgradable to Android 9.0 (Pie), One UI
Chipset is Qualcomm MSM8996 Snapdragon 820 (14 nm)
So it is not using MMAP.

One possibility is that the stop and close of the previous stream failed or did not get called? Can you see them in the log?

Or perhaps the stop/close takes time to settle. Try usleep(500*1000) before restarting the input stream, as an experiment.

Another possibility is that two threads, one from the app and one from the error callback are both affecting the stream. Maybe the app is starting the new stream, then the error callback thread starts the stream again and that fails because it is already started. But maybe not. When I simulate this using OboeTester on a P device. the legacy path does not return -985. 

Is there any chance a BT headset is also paired and it getting connected?

Or, worst case, there is a bug in the S3 that prevents input from being restarted. Can you run OboeTester on the Tab S3 and try the TEST INPUT to see if you can open/start/(start)/stop/close more than once?

**Comment by extreamsd** [comment]
Found it. I deleted both playback and recording streams in onErrorAfterClose(), while onErrorAfterClose() was only called with a disconnect of the playback stream. If I check which stream is passed as argument and delete my reference to it and then close the other (recording) stream, then all is fine. This might explain a couple of crashes that my users are reporting as well.
What is interesting though, is that onErrorAfterClose() is only called with the playback stream as argument when pulling out the headset during recording. No problem for me anymore though, but could cause some confusion.

**Comment by philburk** [comment]
Thanks for the update. I want to make sure I understand this.

Are you using a callback with both input and output? Typically we only use a callback for output and then read() from the input when we handle the output callback.  In this case you will need to stop and close the input after the output is closed.

>  This might explain a couple of crashes that my users are reporting as well.

Maybe. We are seeing more and more evidence that, in P, callbacks to a stream can occur after it has been stopped and closed.

**Comment by extreamsd** [comment]
Ah, now I see the real issue. I have indeed only set the callback on the output, apologies!

**Comment by philburk** [comment]
It sounds like this is resolved so I will close it.
