### ISSUE TITLE
[Question] there is a MIDI synthesizer on oboe?

### ISSUE THREAD

**Issue by diazmanuel** [google/oboe#963]
hi don
i'm starting with this kind of development, actually i am working on a app that take audio from a microphone then apply effects and generate an output to a speaker on real time 
on the app fxlab you do something like that and also you add midi receiver support, but then you dont use it (or that's was i understand)
there is a midi synthesizer on oboe or there will be in the future?

**Comment by philburk** [comment]
We do not have any plans for releasing a MIDI synthesizer for Oboe.
But you can certainly combine MIDI with Oboe in your own app.

For example:
    https://github.com/VolcanoMobile/fluidsynth-android
    https://github.com/search?q=android+MIDI+synthesizer

Android MIDI User Guide: https://developer.android.com/reference/android/media/midi/package-summary

Example apps: https://source.android.com/devices/audio/midi_test#apps

> on the app fxlab you do something like that and also you add midi receiver support,

The fxlab app does not use MIDI. But it looks like it does on GitHub because there was a patch that references MIDI that also changed some files in fxlab.
