### ISSUE TITLE
Moto g6 play cannot play correctly on native buffer size

### ISSUE THREAD

**Issue by extreamsd** [google/oboe#964]
Android version(s): 28
Android device(s): moto g(6) play
Oboe version: 1.4.2
App name used for testing: Audio Evolution Mobile Studio
 
**Short description**
Sound is garbled when playing using AAudio on the native buffer size

**Steps to reproduce**
Select instrument, play on the virtual keyboard

**Expected behavior**
Play without artefacts

**Actual behavior**
Heavy distorted sound

**Any additional context**

With Audio Evolution Mobile Studio v5, we switched the default audio system to be Oboe/AAudio and set the sample rate to the native sample rate. This has not gone without issues. I understand this is not easy for you as well because of the massive number of different Android devices, but surely this has caused several 1-star reviews.

We don't have the moto g6 in question, but the log states:
CREATE OBOE PLAY STREAM, i_nativeSampleRate = 48000 (main sr = 48000), i_nativeBufferSize = 240, i_oboeBufferSizeFactor = 1
Play format = 4, usesAAudio = 1, frames/burst = 240, frames/cb = 240, buffersize = 480, capacity = 1924, low latency = 0, factor = 1

Nothing fancy, just optimal settings to play with the lowest latency on a virtual keyboard. I asked the user to enable the 'Force OpenSLES' option in the app or switch the buffer size to a factor of 2 if that didn't help (which would result in 480 frames/cb) and he says either option solves the problem. I'm seeing more often that forcing OpenSLES using the same buffer size solves audio problems. I would have hoped AAudio to be better regarding this, but unfortunately it isn't always. Do you want me to continue reporting device-specific issues like this even though I don't have the device myself? I do have a video of the user playing the keyboard with garbled sound if you want to see it.

**Comment by extreamsd** [comment]
Forgot to mention: looking at the number of xruns also says nothing unfortunately, since it often reports xruns when audio is playing fine.

**Comment by rpattabi** [comment]
While I'm interested to know about response from oboe team, I just want to provide some points based on experience with our app:

Could this be a scenario where the user connected a bluetooth speaker?  In such a case, using phone's native buffer size may not be sufficient. Typically bluetooth devices need much higher buffer sizes to avoid glitchy playback.

Regarding xruns, when this number is low, we may not sense the glitchy playback. But xruns definitely indicate there is a problem and shall be taken seriously.

In your case, I suspect this is mainly about re-adjusting buffer size according to the playback device. It is best to leave it to oboe to optimize the buffer size rather than we forcing it to native buffer size or something similar. I think it is recommended to have frames per callback at least twice the frames per burst.

**Comment by extreamsd** [comment]
No BT was involved

**Comment by philburk** [comment]
Thanks for this report. There are so many Android phones and we cannot test them in house. We appreciate hearing back about how they perform.

>  I asked the user to enable the 'Force OpenSLES' option in the app or switch the buffer size to a factor of 2 if
> that didn't help (which would result in 480 frames/cb) and he says either option solves the problem.

OK, then the CPU is able to keep up with the workload in the long run. But it is glitching when the buffer size is small, probably due to scheduling jitter and preemption.

Increasing the buffer size is a reasonable solution. I need to define some terms to avoid confusion:

- "Frames Per Burst" is the number of frames that are processed by the DSP or the mixer in one shot.
- "Buffer Capacity" is the number of frames that have been allocated for the buffer. It is a usually a multiple of the "Frames Per Burst".
- "Buffer Size" is the number of frames that are considered to be a full buffer. The size can be adjusted dynamically. Higher Buffer Sizes will be more immune to glitches ("xRuns") but will also have higher latency. You generally want to have the lowest possible Buffer Size that does not glitch.

On many devices, you will glitch if you only have a  Buffer Size of one burst. We recommend two or three bursts to be safe. OpenSL ES uses two bursts.

@extreamsd - Were you seeing XRuns at one burst size? When you see XRuns you should increase the buffer size.

>  looking at the number of xruns also says nothing unfortunately, since it often reports xruns when audio is playing fine.

If you get an XRun when there is silence then you not hear the XRun. Also XRuns may be masked by transients or pops that are part of the original sound. Also some XRuns can occur when a stream is first started.

> Do you want me to continue reporting device-specific issues like this even though I don't have the device myself?

Yes, please. It is helpful to know what buffer size is required on which device.

**Comment by extreamsd** [comment]
frames/burst = 240, frames/cb = 240, buffersize = 480, capacity = 1924

So the buffer size was twice the frames/burst. AEM does not allow lower than that (our factor 1 or so-called native buffer size causes the frames/cb to be the native buffer size and the buffer size is always twice that) . I don't have the device here, but if the user just switched on 'Force OpenSLES', then the same buffer sizes would have been used and OpenSLES played fine where AAudio did not. We can't buy all devices to check though.

I still think the "Higher Buffer Sizes will be more immune to glitches" is flawed. I posted before on the Latency Tuner being no use, simply because CPU usage is determined by frames/callback and that doesn't change when increasing the buffer size. Only if the Latency Tuner could increase the frames/callback as well, then there would be less glitches: if you would call the callback 4 times in a row with 64 frames, it would cause significantly more CPU usage than calling the callback once with 256 frames.

**Comment by philburk** [comment]
AAudio on a Moto G6 should be using most of the same Legacy data path as OpenSL ES. So I think the difference is in the buffer parameters.

> I don't have the device here, but if the user just switched on 'Force OpenSLES', then the same buffer
> sizes would have been used...

Not necessarily.  OpenSL ES and AAudio often do not have the same burst sizes. The buffer sizes and capacity can also be different.

AAudio has a burst of 96 frames on a Pixel 3a and 256 frames on my Android Go device.
OpenSL ES has a burst of 192 frames on both devices.

> frames/burst = 240, frames/cb = 240, buffersize = 480, capacity = 1924

Are you calling builder->setFramesPerCallback(240) or is 240 the size you got from the device?
On OpenSL ES, that will result in the burst size being set to 240.
On AAudio MMAP, the burst size should still be determined by the device.
On a LowLatency stream I see that the burst is still 96.
But on a **not**-LowLatency stream the burst size is 240 and I am seeing glitching!
Normally on this stream the burst would be 1922 frames.
Perhaps this is what you are seeing. Are you requesting a LowLatency stream?

Thanks for reporting this.

**Comment by philburk** [comment]
> I still think the "Higher Buffer Sizes will be more immune to glitches" is flawed.

Generally the glitching is due to scheduling jitter or preemption of the audio thread, which can result in the buffer underflowing. If there is more data in the buffer then you can be preempted for a longer time without underflowing.
 
> because CPU usage is determined by frames/callback

The CPU usage per callback is roughly proportional to the frames per callback. Having more frames per callback is more efficient because there is some fixed overhead per callback but it is usually not significant.

If the glitching is due to the CPU simply not being able to provide frames in real time then the only way to prevent that is to reduce the computational workload per frame, or convince the CPU to increase the CPU clock frequency.

**Comment by extreamsd** [comment]
In a true real-time audio thread, preemption cannot occur. I am still fully convinced that the latency tuner does not do a thing. I can see it happening here. Let's say the latency tuner increased the buffer size by a factor of 4, then glitching would still occur. Stopping and changing the frames/callback instead will stop the glitching to occur. I have the feeling you should really try out DAW software like ours with 16 tracks or so and many effects. That is entirely different than playing one synth or so since the overhead of all those elements in the audio processing chain becomes significant.

**Comment by extreamsd** [comment]
I am using setFramesPerCallback() indeed and requesting the low latency mode when the sample rate matches the native sample rate.

**Comment by philburk** [comment]
Thanks for reporting this.  I created a bug focussed on this and the workaround and will DUP to that bug.
